#!/usr/bin/env python3
"""Shared list filters for the IPTV hunt."""

from __future__ import annotations

MIN_VOLUME = 500

# Country-code hunt order: CA, US, then Europe. `.ie` is never listed.
COUNTRY_TLD_LABELS = [
    ("ca", "Canada"),
    ("us", "United States"),
    ("fr", "France"),
    ("de", "Germany"),
    ("nl", "Netherlands"),
    ("ch", "Switzerland"),
    ("be", "Belgium"),
    ("at", "Austria"),
    ("es", "Spain"),
    ("it", "Italy"),
    ("pt", "Portugal"),
    ("se", "Sweden"),
    ("no", "Norway"),
    ("dk", "Denmark"),
    ("fi", "Finland"),
    ("pl", "Poland"),
    ("cz", "Czechia"),
    ("eu", "EU (.eu)"),
    ("co.uk", "United Kingdom"),
]


# Longest-first tokens so compareiptv → compare + iptv, not leftover junk.
_WORD_TOKENS = tuple(
    sorted(
        {
            "kaufen",
            "billig",
            "decoder",
            "epg",
            "catchup",
            "replay",
            "sport",
            "movie",
            "films",
            "film",
            "chaines",
            "sender",
            "kanal",
            "stb",
            "kids",
            "news",
            "pvr",
            "timeshift",
            "install",
            "config",
            "hdr",
            "hevc",
            "bouquet",
            "pack",
            "line",
            "mac",
            "dns",
            "backup",
            "vpn",
            "orleans",
            "tours",
            "metz",
            "mulhouse",
            "caen",
            "avignon",
            "surrey",
            "burnaby",
            "richmond",
            "markham",
            "vaughan",
            "milwaukee",
            "pittsburgh",
            "cincinnati",
            "stlouis",
            "mannheim",
            "augsburg",
            "wiesbaden",
            "haarlem",
            "zwolle",
            "maastricht",
            "fribourg",
            "sion",
            "umea",
            "kristiansand",
            "esbjerg",
            "randers",
            "lahti",
            "kuopio",
            "arabe",
            "maroc",
            "tunisie",
            "algerie",
            "maghreb",
            "latino",
            "brasil",
            "turc",
            "pau",
            "poitiers",
            "brest",
            "lemans",
            "pinoy",
            "desi",
            "grec",
            "polonais",
            "hindi",
            "family",
            "hotel",
            "ultra",
            "lite",
            "mini",
            "home",
            "cafe",
            "plus",
            "multi",
            "max",
            "fibre",
            "parabole",
            "tnt",
            "satellite",
            "cable",
            "cord",
            "cut",
            "wifi",
            "hdmi",
            "usb",
            "adsl",
            "radio",
            "anime",
            "series",
            "podcast",
            "docu",
            "cinema",
            "karaoke",
            "fitness",
            "golf",
            "racing",
            "soccer",
            "football",
            "rugby",
            "nhl",
            "nba",
            "ufc",
            "foot",
            "cricket",
            "tennis",
            "boxing",
            "mma",
            "nascar",
            "ligue",
            "premier",
            "formula",
            "motogp",
            "wwe",
            "pga",
            "euro",
            "worldcup",
            "champions",
            "norsk",
            "dansk",
            "vlaams",
            "quebecois",
            "albi",
            "gap",
            "medicinehat",
            "desmoines",
            "boise",
            "paderborn",
            "hildesheim",
            "helmond",
            "veenendaal",
            "motor",
            "nordic",
            "valais",
            "vaud",
            "alsace",
            "bretagne",
            "corse",
            "provence",
            "calais",
            "dunkerque",
            "thunderbay",
            "spokane",
            "reno",
            "trier",
            "coburg",
            "alkmaar",
            "hoorn",
            "region",
            "coast",
            "normandie",
            "aquitaine",
            "savoie",
            "jura",
            "bayern",
            "sachsen",
            "brabant",
            "limburg",
            "rouen",
            "cherbourg",
            "whitehorse",
            "yellowknife",
            "anchorage",
            "honolulu",
            "rostock",
            "schwerin",
            "leeuwarden",
            "island",
            "lake",
            "nrw",
            "hessen",
            "friesland",
            "gelderland",
            "languedoc",
            "ticino",
            "vestland",
            "gotland",
            "lapland",
            "bastia",
            "ajaccio",
            "iqaluit",
            "juneau",
            "flensburg",
            "emmen",
            "highland",
            "valley",
            "catalan",
            "catala",
            "basque",
            "wallon",
            "sami",
            "carcassonne",
            "billings",
            "bozeman",
            "cottbus",
            "goerlitz",
            "hoogeveen",
            "forest",
            "river",
            "amazigh",
            "kabyle",
            "creole",
            "antilles",
            "reunion",
            "guyane",
            "tahiti",
            "caledonie",
            "hilo",
            "bay",
            "martinique",
            "guadeloupe",
            "mayotte",
            "polynesie",
            "swiss",
            "romandie",
            "arles",
            "narbonne",
            "setes",
            "fairbanks",
            "wuppertal",
            "bochum",
            "zaandam",
            "harbour",
            "port",
            "bundesliga",
            "eredivisie",
            "laliga",
            "seriea",
            "ligue1",
            "xiaomi",
            "onn",
            "tcl",
            "googletv",
            "firecube",
            "cube",
            "occitan",
            "breton",
            "picard",
            "romansh",
            "alsacien",
            "saintpierre",
            "wallis",
            "futuna",
            "neuchatel",
            "aargau",
            "thurgau",
            "graubunden",
            "darts",
            "snooker",
            "cycling",
            "hockey",
            "handball",
            "ski",
            "troyes",
            "brive",
            "agen",
            "montauban",
            "rodez",
            "foix",
            "mende",
            "chalons",
            "auxerre",
            "chartres",
            "sherbrooke",
            "moncton",
            "saintjohn",
            "charlottetown",
            "fredericton",
            "troisrivieres",
            "saguenay",
            "barrie",
            "guelph",
            "birmingham",
            "knoxville",
            "madison",
            "littlerock",
            "albuquerque",
            "richmondva",
            "norfolk",
            "buffalo",
            "rochester",
            "kaiserslautern",
            "passau",
            "bamberg",
            "kempten",
            "wuerzburg",
            "freiburg",
            "regensburg",
            "doetinchem",
            "assen",
            "middelburg",
            "vlissingen",
            "denbosch",
            "gouda",
            "chur",
            "thun",
            "biel",
            "aarau",
            "schaffhausen",
            "locarno",
            "montreux",
            "bodo",
            "alesund",
            "drammen",
            "herning",
            "vejle",
            "kolding",
            "roskilde",
            "vaasa",
            "joensuu",
            "pori",
            "rovaniemi",
            "vasteras",
            "norrkoping",
            "helsingborg",
            "jonkoping",
            "lulea",
            "channel",
            "county",
            "village",
            "moor",
            "fell",
            "canal",
            "hisense",
            "philips",
            "samsung",
            "sony",
            "flemish",
            "frisian",
            "kurdish",
            "armenian",
            "yiddish",
            "romani",
            "auvergne",
            "champagne",
            "lorraine",
            "picardie",
            "poitou",
            "limousin",
            "saarland",
            "thueringen",
            "brandenburg",
            "mecklenburg",
            "zeeland",
            "drenthe",
            "overijssel",
            "flevoland",
            "appenzell",
            "glarus",
            "schwyz",
            "zug",
            "ligue2",
            "copa",
            "olympics",
            "sixnations",
            "infomir",
            "mag254",
            "roubaix",
            "tourcoing",
            "cergy",
            "evry",
            "nanterre",
            "saintnazaire",
            "laon",
            "beauvais",
            "compiegne",
            "oshawa",
            "milton",
            "ajax",
            "pickering",
            "princegeorge",
            "lethbridge",
            "stjohns",
            "sudbury",
            "charleston",
            "savannah",
            "greensboro",
            "durham",
            "tacoma",
            "oakland",
            "heidelberg",
            "karlsruhe",
            "potsdam",
            "dordrecht",
            "zoetermeer",
            "hilversum",
            "ede",
            "oss",
            "spijkenisse",
            "yverdon",
            "nyon",
            "vevey",
            "bellinzona",
            "solothurn",
            "harstad",
            "molde",
            "lillehammer",
            "silkeborg",
            "holstebro",
            "naestved",
            "horsens",
            "kotka",
            "mikkeli",
            "hameenlinna",
            "gavle",
            "karlstad",
            "sundsvall",
            "wales",
            "scotland",
            "ulster",
            "midlands",
            "yorkshire",
            "cornwall",
            "devon",
            "kent",
            "fiber",
            "dsl",
            "gigabit",
            "mlb",
            "nfl",
            "mls",
            "cfl",
            "punjabi",
            "tamil",
            "urdu",
            "farsi",
            "wolof",
            "swahili",
            "bollywood",
            "kdrama",
            "telenovela",
            "vendee",
            "charente",
            "ardeche",
            "lozere",
            "paysbasque",
            "ruhr",
            "eifel",
            "harz",
            "schwarzwald",
            "veluwe",
            "wadden",
            "engadin",
            "millau",
            "cahors",
            "dax",
            "carpentras",
            "draguignan",
            "peterborough",
            "belleville",
            "sarnia",
            "fargo",
            "siouxfalls",
            "springfield",
            "luebeck",
            "chemnitz",
            "halle",
            "purmerend",
            "amstelveen",
            "davos",
            "interlaken",
            "zermatt",
            "fredrikstad",
            "sandnes",
            "viborg",
            "seinajoki",
            "visby",
            "cotswold",
            "lakes",
            "peak",
            "suffolk",
            "essex",
            "sussex",
            "surrey",
            "cantonese",
            "mandarin",
            "vietnamese",
            "thai",
            "korean",
            "japanese",
            "filipino",
            "mecool",
            "minix",
            "beelink",
            "ugoos",
            "ncaa",
            "wnba",
            "ariege",
            "aveyron",
            "gers",
            "landes",
            "allgaeu",
            "ostfriesland",
            "twente",
            "oberland",
            "mittelland",
            "aurillac",
            "tulle",
            "gueret",
            "brantford",
            "welland",
            "cornwall",
            "topeka",
            "lincoln",
            "giessen",
            "marburg",
            "siegen",
            "weert",
            "roermond",
            "grindelwald",
            "brig",
            "visp",
            "haugesund",
            "porsgrunn",
            "koge",
            "holbaek",
            "lappeenranta",
            "falun",
            "borlange",
            "dales",
            "fens",
            "downs",
            "weald",
            "shire",
            "mersey",
            "tyne",
            "forth",
            "romanian",
            "hungarian",
            "czech",
            "slovak",
            "serbian",
            "croatian",
            "bulgarian",
            "zidoo",
            "tanix",
            "creuse",
            "correze",
            "cantal",
            "sauerland",
            "spreewald",
            "muensterland",
            "achterhoek",
            "betuwe",
            "emmental",
            "simmental",
            "figeac",
            "woodstock",
            "rapidcity",
            "fulda",
            "wetzlar",
            "sittard",
            "kerkrade",
            "sierre",
            "martigny",
            "skien",
            "slagelse",
            "savonlinna",
            "ostersund",
            "kiruna",
            "thames",
            "severn",
            "wye",
            "avon",
            "clyde",
            "tay",
            "spey",
            "ukrainian",
            "lithuanian",
            "latvian",
            "estonian",
            "homatics",
            "wetek",
            "droidbox",
            "sarthe",
            "mayenne",
            "lausitz",
            "erzgebirge",
            "mosel",
            "kempen",
            "peel",
            "seeland",
            "auch",
            "chatham",
            "bismarck",
            "bayreuth",
            "offenburg",
            "venray",
            "monthey",
            "hamar",
            "ringsted",
            "imatra",
            "skelleftea",
            "solent",
            "humber",
            "trent",
            "ouse",
            "tees",
            "tamar",
            "albanian",
            "bosnian",
            "macedonian",
            "gtmedia",
            "octagon",
            "morbihan",
            "finistere",
            "pfalz",
            "rhein",
            "orkney",
            "shetland",
            "anglesey",
            "skye",
            "slovenian",
            "georgian",
            "azeri",
            "kazakh",
            "somali",
            "yoruba",
            "dari",
            "pashto",
            "dreambox",
            "mutant",
            "vaucluse",
            "drome",
            "holstein",
            "westfalen",
            "sete",
            "agde",
            "orillia",
            "duluth",
            "greenbay",
            "hof",
            "plauen",
            "tiel",
            "culemborg",
            "aigle",
            "alta",
            "kirkenes",
            "hobro",
            "rauma",
            "pitea",
            "hebrides",
            "wight",
            "scilly",
            "manx",
            "amharic",
            "hausa",
            "igbo",
            "edision",
            "gigablue",
            "var",
            "gard",
            "niederrhein",
            "nordsee",
            "oromo",
            "akan",
            "zulu",
            "qviart",
            "axas",
            "herault",
            "aude",
            "ostsee",
            "elbe",
            "lunel",
            "timmins",
            "appleton",
            "zwickau",
            "wageningen",
            "boudry",
            "vardo",
            "skagen",
            "raahe",
            "kalix",
            "pentland",
            "minch",
            "khmer",
            "lao",
            "myanmar",
            "amiko",
            "opticum",
            "tarn",
            "weser",
            "oder",
            "frontignan",
            "thompson",
            "racine",
            "gera",
            "barneveld",
            "payerne",
            "hammerfest",
            "hirtshals",
            "kemi",
            "gallivare",
            "moray",
            "nairn",
            "tibetan",
            "mongolian",
            "uzbek",
            "protek",
            "azbox",
            "cevennes",
            "camargue",
            "spree",
            "havel",
            "mauguio",
            "kenora",
            "kenosha",
            "jena",
            "nijkerk",
            "morges",
            "vadso",
            "frederikshavn",
            "tornio",
            "jokkmokk",
            "speyside",
            "cairngorm",
            "kyrgyz",
            "tajik",
            "turkmen",
            "nepali",
            "bengali",
            "openbox",
            "skybox",
            "icecrypt",
            "vuplus",
            "pyrenees",
            "vosges",
            "ardennes",
            "ferguson",
            "snowdon",
            "trossachs",
            "pennine",
            "cheviot",
            "brecon",
            "telugu",
            "malayalam",
            "sinhala",
            "kannada",
            "gujarati",
            "maxytec",
            "xsarius",
            "mendip",
            "chiltern",
            "quantock",
            "malvern",
            "marathi",
            "assamese",
            "odia",
            "konkani",
            "tigrinya",
            "shona",
            "xhosa",
            "osmio",
            "vusolo",
            "dordogne",
            "allier",
            "nievre",
            "dartmoor",
            "exmoor",
            "newforest",
            "bhojpuri",
            "sindhi",
            "kashmiri",
            "lingala",
            "kinyarwanda",
            "tswana",
            "vuuno",
            "vuultimo",
            "vuzero",
            "yonne",
            "loiret",
            "calvados",
            "pembroke",
            "gwynedd",
            "powys",
            "maithili",
            "meitei",
            "dogri",
            "luganda",
            "bambara",
            "vuduo",
            "k1plus",
            "cumbria",
            "durham",
            "cheshire",
            "rajasthani",
            "haryanvi",
            "santali",
            "sotho",
            "chewa",
            "vustorm",
            "aisne",
            "aube",
            "armor",
            "shropshire",
            "stafford",
            "lincoln",
            "ndebele",
            "dagbani",
            "miraclebox",
            "jynxbox",
            "doubs",
            "meuse",
            "moselle",
            "basrhin",
            "hautrhin",
            "derbyshire",
            "leicester",
            "nottingham",
            "worcester",
            "hereford",
            "walloon",
            "corsican",
            "galician",
            "sicilian",
            "sardinian",
            "friulian",
            "faroese",
            "greenlandic",
            "inuktitut",
            "ojibwe",
            "uclan",
            "starbox",
            "isere",
            "ladino",
            "somerset",
            "wiltshire",
            "hampshire",
            "oxfordshire",
            "gloucester",
            "bedford",
            "hertford",
            "cornish",
            "gaelic",
            "welsh",
            "asturian",
            "aragonese",
            "mikmaq",
            "mohawk",
            "anadol",
            "puydedome",
            "cotedor",
            "berkshire",
            "buckingham",
            "northampton",
            "warwickshire",
            "rutland",
            "luxembourgish",
            "scots",
            "walser",
            "ladin",
            "innu",
            "haida",
            "hautevienne",
            "deuxsevres",
            "charentemaritime",
            "dorset",
            "cambridgeshire",
            "lancashire",
            "merseyside",
            "tyneside",
            "bayonne",
            "tarbes",
            "nanaimo",
            "kamloops",
            "elpaso",
            "wichita",
            "ulm",
            "konstanz",
            "venlo",
            "heerlen",
            "saintetienne",
            "abbotsford",
            "tucson",
            "fresno",
            "aachen",
            "mainz",
            "enschede",
            "quimper",
            "vannes",
            "lorient",
            "reddeer",
            "omaha",
            "tulsa",
            "magdeburg",
            "erfurt",
            "apeldoorn",
            "beziers",
            "nimes",
            "colmar",
            "kingston",
            "niagara",
            "louisville",
            "kassel",
            "kiel",
            "amersfoort",
            "valence",
            "niort",
            "larochelle",
            "kitchener",
            "waterloo",
            "memphis",
            "jacksonville",
            "bielefeld",
            "muenster",
            "leiden",
            "delft",
            "romand",
            "wallonie",
            "tessin",
            "clermont",
            "limoges",
            "amiens",
            "perpignan",
            "baltimore",
            "sacramento",
            "raleigh",
            "saltlake",
            "gatineau",
            "laval",
            "bremen",
            "dortmund",
            "essen",
            "almere",
            "arnhem",
            "nijmegen",
            "luzern",
            "stgallen",
            "orebro",
            "linkoping",
            "tromso",
            "aalborg",
            "jyvaskyla",
            "grenoble",
            "toulon",
            "lehavre",
            "kelowna",
            "windsor",
            "saskatoon",
            "philadelphia",
            "minneapolis",
            "tampa",
            "orlando",
            "cleveland",
            "columbus",
            "indianapolis",
            "hannover",
            "leipzig",
            "dresden",
            "nurnberg",
            "groningen",
            "tilburg",
            "breda",
            "trondheim",
            "stavanger",
            "odense",
            "oulu",
            "turku",
            "goteborg",
            "uppsala",
            "lugano",
            "winterthur",
            "kodi",
            "downloader",
            "enigma",
            "zgemma",
            "norge",
            "danmark",
            "suomi",
            "sverige",
            "chicago",
            "phoenix",
            "strasbourg",
            "rennes",
            "montpellier",
            "stockholm",
            "malmo",
            "aanbieder",
            "proberen",
            "abbonamento",
            "suscripcion",
            "legale",
            "deutschland",
            "vlc",
            "prueba",
            "prova",
            "barato",
            "vergelijk",
            "halpa",
            "miglior",
            "abonnement",
            "comparateur",
            "comparatif",
            "classement",
            "anbietervergleich",
            "aanbieders",
            "vergelijken",
            "vergelijker",
            "vergleicher",
            "vergleich",
            "streaming",
            "firestick",
            "androidtv",
            "android",
            "appletv",
            "smarters",
            "tivimate",
            "formuler",
            "canadian",
            "canada",
            "quebec",
            "ontario",
            "france",
            "deutsch",
            "nederland",
            "belgique",
            "belgie",
            "schweiz",
            "suisse",
            "meilleur",
            "pascher",
            "compare",
            "comparer",
            "stream",
            "watch",
            "guide",
            "avis",
            "essai",
            "test",
            "trial",
            "forfait",
            "abo",
            "liste",
            "legal",
            "reddit",
            "player",
            "picks",
            "plans",
            "rank",
            "rating",
            "review",
            "reviews",
            "deals",
            "cheap",
            "best",
            "beste",
            "bedste",
            "paras",
            "basta",
            "sammenlign",
            "vertaa",
            "jamfor",
            "iptv",
            "live",
            "box",
            "ott",
            "tv",
            "4k",
            "usa",
            "uk",
            "nl",
            "de",
            "fr",
            "ch",
            "be",
            "no",
            "dk",
            "fi",
            "nord",
            "maple",
            "roku",
            "samsung",
            "cordcut",
            "cordcutter",
            "cutthecord",
            "smarttv",
            "smarter",
            "xtream",
            "m3u",
            "mag",
            "stick",
            "apps",
            "app",
            "gids",
            "opas",
            "pruvodce",
            "przewodnik",
            "guia",
            "guida",
            "confronta",
            "comparar",
            "mejor",
            "migliore",
            "melhor",
            "najlepszy",
            "nejlepsi",
            "porownaj",
            "srovnani",
            "ratgeber",
            "anbieter",
            "goedkoop",
            "goedkope",
            "guenstig",
            "guenstige",
            "houston",
            "dallas",
            "miami",
            "atlanta",
            "seattle",
            "denver",
            "boston",
            "detroit",
            "philadelphia",
            "lasvegas",
            "portland",
            "nashville",
            "austin",
            "charlotte",
            "toronto",
            "montreal",
            "vancouver",
            "calgary",
            "ottawa",
            "edmonton",
            "winnipeg",
            "halifax",
            "hamilton",
            "kelowna",
            "regina",
            "saskatoon",
            "victoria",
            "mississauga",
            "brampton",
            "laval",
            "gatineau",
            "windsor",
            "london",
            "alberta",
            "manitoba",
            "atlantic",
            "sask",
            "bc",
            "kw",
            "berlin",
            "hamburg",
            "muenchen",
            "frankfurt",
            "stuttgart",
            "koeln",
            "duesseldorf",
            "amsterdam",
            "rotterdam",
            "utrecht",
            "eindhoven",
            "denhaag",
            "zurich",
            "geneve",
            "lausanne",
            "bern",
            "basel",
            "oslo",
            "bergen",
            "kobenhavn",
            "aarhus",
            "helsinki",
            "tampere",
            "paris",
            "lyon",
            "marseille",
            "toulouse",
            "lille",
            "nantes",
            "bordeaux",
            "nice",
            "reims",
            "dijon",
            "angers",
            "madrid",
            "barcelona",
            "roma",
            "milano",
            "lisboa",
            "wien",
            "praha",
            "warszawa",
            "chooser",
            "checker",
            "compareott",
            "paytv",
            "playlist",
            "subscription",
            "reseller",
            "server",
            "panel",
            "portal",
            "codes",
            "setup",
            "navigator",
            "premium",
            "vod",
            "formuler",
            "xciptv",
            "extreme",
            "duplex",
            "televizo",
            "sparkle",
            "xeplayer",
            "myiptv",
            "xtream",
            "enigma",
            "zgemma",
            "buzztv",
            "dreamlink",
            "nvidia",
            "shield",
            "firetv",
            "chromecast",
            "smart",
            "tivi",
            "mate",
        },
        key=len,
        reverse=True,
    )
)


def domain_label(domain: str) -> str:
    d = domain.lower().strip()
    if d.endswith(".co.uk"):
        return d[: -len(".co.uk")]
    if d.endswith(".com.au"):
        return d[: -len(".com.au")]
    if "." in d:
        return d.rsplit(".", 1)[0]
    return d


def _tokenize_piece(piece: str) -> list[str]:
    s = piece.lower()
    out: list[str] = []
    i = 0
    while i < len(s):
        hit = None
        for tok in _WORD_TOKENS:
            if s.startswith(tok, i):
                hit = tok
                break
        if hit:
            out.append(hit)
            i += len(hit)
            continue
        out.append(s[i:])
        break
    return out


def domain_word_count(domain: str) -> int:
    """Hyphen parts plus smashed words inside each part (compareiptv = 2)."""
    label = domain_label(domain)
    if not label:
        return 0
    total = 0
    for part in label.replace("_", "-").split("-"):
        if not part:
            continue
        total += len(_tokenize_piece(part))
    return total


def is_two_word_domain(domain: str) -> bool:
    return domain_word_count(domain) == 2


def skip_domain(domain: str) -> bool:
    if domain.endswith(".ie"):
        return True
    if "iptv" in domain and (domain.endswith(".uk") or domain.endswith(".co.uk")):
        return True
    if not is_two_word_domain(domain):
        return True
    return False


def tld_key(domain: str) -> str:
    if domain.endswith(".co.uk"):
        return "co.uk"
    if domain.endswith(".com.au"):
        return "com.au"
    return domain.rsplit(".", 1)[-1]


def verdict_bucket(verdict: str) -> str:
    v = (verdict or "").strip()
    if v == "AVAILABLE":
        return "AVAILABLE"
    if v == "TAKEN":
        return "TAKEN"
    if v == "UNKNOWN":
        return "UNKNOWN"
    return "CONFIRM"


def country_tld_groups(recheck: dict[str, dict]) -> dict[str, dict[str, list[str]]]:
    """AVAILABLE / TAKEN / CONFIRM / UNKNOWN names per country TLD."""
    out: dict[str, dict[str, list[str]]] = {}
    for tld, _label in COUNTRY_TLD_LABELS:
        out[tld] = {"AVAILABLE": [], "TAKEN": [], "CONFIRM": [], "UNKNOWN": []}
    for domain, row in recheck.items():
        if skip_domain(domain):
            continue
        tld = tld_key(domain)
        if tld not in out:
            continue
        out[tld][verdict_bucket(row.get("verdict") or "")].append(domain)
    for tld in out:
        for k in out[tld]:
            out[tld][k].sort()
    return out


def opportunity_score(volume: int, kd: int) -> float:
    """Higher is better: more searches, lower keyword difficulty."""
    kd = max(0, min(100, int(kd)))
    return round(volume * (100 - kd) / 100.0, 1)


# Semrush "Difficult" (and harder) is out of the buy/score lists.
_EXCLUDED_KD = {"difficult", "very hard", "super hard"}

# When a domain was mapped to a Difficult head term, use the next verified easier keyword.
DIFFICULT_FALLBACK = {
    "iptv": "best iptv",
    "iptv canada": "best iptv canada",
}


def kd_is_excluded(k: dict | None) -> bool:
    if not k:
        return False
    lab = str(k.get("kd_label") or "").strip().lower()
    if lab in _EXCLUDED_KD:
        return True
    return "difficult" in lab


def keyword_volume(traffic: dict, name: str | None) -> int | None:
    if not name:
        return None
    k = (traffic.get("keywords") or {}).get(name)
    if not k:
        return None
    try:
        return int(k["volume"])
    except (KeyError, TypeError, ValueError):
        return None


def meets_volume(traffic: dict, name: str | None) -> bool:
    vol = keyword_volume(traffic, name)
    return vol is not None and vol >= MIN_VOLUME


def meets_opportunity(traffic: dict, name: str | None) -> bool:
    """Volume >= 500 and KD is not Difficult."""
    if not meets_volume(traffic, name):
        return False
    k = (traffic.get("keywords") or {}).get(name)
    return not kd_is_excluded(k)


def mapped_keyword(traffic: dict, domain: str) -> str | None:
    kw = (traffic.get("domain_keyword_map") or {}).get(domain)
    if not kw:
        return None
    kws = traffic.get("keywords") or {}
    if kd_is_excluded(kws.get(kw)):
        fb = DIFFICULT_FALLBACK.get(kw)
        if fb and meets_opportunity(traffic, fb):
            return fb
        return None
    return kw


def domain_meets_volume(traffic: dict, domain: str) -> bool:
    return meets_opportunity(traffic, mapped_keyword(traffic, domain))


PREFERRED_DOMAINS = (
    "compareriptv.fr",
    "avis-iptv.fr",
    "comparateur-iptv.fr",
    "pascheriptv.fr",
    "essaiiptv.fr",
    "guideiptv.fr",
    "compareiptv.ca",
    "iptvguide.ca",
    "iptvcompare.ca",
    "compareriptv.ca",
    "avis-iptv.ca",
    "guideiptv.ca",
    "compareiptv.fr",
    "compareiptv.us",
    "avis-iptv.us",
    "firestick-guide.us",
    "iptv-server.ca",
    "iptvbox.ca",
    "iptv-box.ca",
    "iptv-player.ca",
    "box-avis.fr",
    "iptv-server.fr",
    "firestick-iptv.us",
    "android-iptv.us",
)


def rank_available_domains(traffic: dict, recheck: dict, limit: int = 10, per_keyword: int = 3) -> list[dict]:
    """AVAILABLE names, volume >= 500, sorted by high traffic and low KD."""
    scored = []
    kws = traffic.get("keywords") or {}
    for domain, row in recheck.items():
        if row.get("verdict") != "AVAILABLE":
            continue
        if skip_domain(domain):
            continue
        kw = mapped_keyword(traffic, domain)
        if not meets_opportunity(traffic, kw):
            continue
        k = kws[kw]
        vol = int(k["volume"])
        kd = int(k["kd"])
        scored.append(
            {
                "domain": domain,
                "keyword": kw,
                "volume": vol,
                "volume_display": k.get("volume_display"),
                "kd": kd,
                "kd_label": k.get("kd_label"),
                "cpc": k.get("cpc"),
                "db": k.get("db"),
                "score": opportunity_score(vol, kd),
                "preferred": domain in PREFERRED_DOMAINS,
            }
        )
    scored.sort(key=lambda r: (-r["score"], 0 if r["preferred"] else 1, len(r["domain"]), r["domain"]))
    out: list[dict] = []
    seen_kw: set[str] = set()
    for row in scored:
        if row["keyword"] in seen_kw:
            continue
        if row["db"] == "ie":
            continue
        seen_kw.add(row["keyword"])
        out.append(row)
        if len(out) >= limit:
            return out
    counts = {row["keyword"]: 1 for row in out}
    taken = {row["domain"] for row in out}
    for row in scored:
        if row["domain"] in taken:
            continue
        n = counts.get(row["keyword"], 0)
        if n >= per_keyword:
            continue
        counts[row["keyword"]] = n + 1
        out.append(row)
        taken.add(row["domain"])
        if len(out) >= limit:
            break
    return out
