#!/usr/bin/env python3
"""One ranked keyword table. Real queries only (no Semrush 'a - b' pair rows). No invented volumes."""

from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path

from filters import MIN_VOLUME, domain_label, kd_is_excluded, skip_domain, skip_keyword

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "RANKED_KEYWORDS.md"
TRAFFIC = ROOT / "canva" / "traffic.json"
RECHECK = ROOT / "availability_recheck.csv"

# Markets the user asked to hunt: CA / US / UK / Scandinavia — not .fr leftovers.
FOCUS_DB = {"ca", "us", "uk", "se", "no", "dk", "fi"}
FOCUS_ENDS = (".ca", ".us", ".dk", ".no", ".se", ".fi", ".co.uk", ".uk")
FOCUS_LABEL = {
    "ca": "Canada",
    "us": "United States",
    "uk": "United Kingdom",
    "se": "Sweden",
    "no": "Norway",
    "dk": "Denmark",
    "fi": "Finland",
}

# Participant queries (spaces, not hyphen-pairs). Queued until Semrush Overview exists.
QUEUED = (
    ("tivimate playlist", "us", "TiviMate playlist commercial"),
    ("tivimate setup", "us", "TiviMate install commercial"),
    ("smarters pro", "us", "IPTV Smarters Pro app"),
    ("ibo player", "us", "IBO Player app"),
    ("ibo pro", "us", "IBO Pro app"),
    ("ott navigator", "us", "OTT Navigator app"),
    ("ott play", "us", "OTTplay app"),
    ("gse smart iptv", "us", "GSE Smart IPTV app"),
    ("xtream codes", "us", "Panel / playlist commercial"),
    ("xciptv", "us", "XCIPTV app"),
    ("televizo", "us", "Televizo app"),
    ("ss iptv", "us", "SS IPTV app"),
    ("smart iptv", "us", "Smart IPTV app"),
    ("kodi iptv", "us", "Kodi + IPTV setup"),
    ("perfect player", "us", "Perfect Player app"),
    ("lazy iptv", "us", "Lazy IPTV app"),
    ("iptv extreme", "us", "IPTV Extreme app"),
    ("duplex iptv", "us", "Duplex IPTV app"),
    ("purple player", "us", "Purple Player app"),
    ("flix iptv", "us", "Flix IPTV app"),
    ("magis tv", "us", "Magis TV app"),
    ("google tv iptv", "us", "Google TV box commercial"),
    ("onn box", "us", "Walmart Onn box"),
    ("xiaomi iptv", "us", "Cheap Android box"),
    ("roku iptv", "us", "Roku + IPTV setup"),
    ("vlc iptv", "us", "VLC + playlist setup"),
    ("apple tv iptv", "us", "Apple TV + IPTV"),
    ("fire cube iptv", "us", "Fire TV Cube + IPTV"),
    ("british iptv", "uk", "UK geo commercial — not .irish"),
    ("beste iptv", "no", "Norwegian best IPTV"),
    ("bedste iptv", "dk", "Danish best IPTV"),
    ("basta iptv", "se", "Swedish best IPTV"),
    ("paras iptv", "fi", "Finnish best IPTV"),
    ("tivimate canada", "ca", "TiviMate + CA geo"),
    ("tivimate firestick", "us", "App + Fire Stick"),
    ("formuler iptv", "us", "Formuler box"),
    ("sparkle iptv", "us", "Sparkle TV app"),
    ("set iptv", "us", "SetIPTV app"),
    ("net iptv", "us", "Net IPTV app"),
    ("enigma iptv", "us", "Enigma box setup"),
    ("iptv downloader", "us", "Downloader + Fire Stick"),
    ("mag 254", "us", "MAG 254 box"),
    ("infomir", "us", "Infomir MAG boxes"),
    ("star box", "us", "StarBox Android box"),
    ("uclan iptv", "uk", "UCLAN box setup"),
    ("vontar box", "us", "Vontar Android box"),
    ("h96 max", "us", "H96 Max box"),
    ("transpeed box", "us", "Transpeed Android box"),
    ("hk1 max", "us", "HK1 Max box"),
    ("x88 pro", "us", "X88 Pro box"),
    ("t95 max", "us", "T95 Max box"),
    ("mxq pro", "us", "MXQ Pro box"),
    ("t95 mini", "us", "T95 Mini box"),
    ("x99 max", "us", "X99 Max box"),
    ("allwinner box", "us", "Allwinner chipset box"),
    ("amlogic box", "us", "Amlogic chipset box"),
    ("rockchip box", "us", "Rockchip chipset box"),
    ("s905x3 box", "us", "S905X3 chipset box"),
    ("s905w2 box", "us", "S905W2 chipset box"),
    ("a311d box", "us", "A311D chipset box"),
    ("s922x box", "us", "S922X chipset box"),
    ("rk3399 box", "us", "RK3399 chipset box"),
    ("s905x2 box", "us", "S905X2 chipset box"),
    ("rk3229 box", "us", "RK3229 chipset box"),
    ("s905l3 box", "us", "S905L3 chipset box"),
    ("rk3288 box", "us", "RK3288 chipset box"),
    ("s905x5 box", "us", "S905X5 chipset box"),
    ("s905l2 box", "us", "S905L2 chipset box"),
    ("mecool box", "us", "Mecool Android box"),
    ("beelink box", "us", "Beelink Android box"),
    ("tanix box", "us", "Tanix Android box"),
    ("zidoo box", "us", "Zidoo media box"),
    ("ugoos box", "us", "Ugoos Android box"),
    ("buzz tv", "us", "BuzzTV Android box"),
    ("dreamlink box", "us", "Dreamlink box"),
    ("zgemma box", "us", "Zgemma Enigma box"),
    ("chromecast iptv", "us", "Chromecast + IPTV"),
    ("nvidia shield", "us", "NVIDIA Shield TV"),
    ("coreelec box", "us", "CoreELEC firmware box"),
    ("rk3528 box", "us", "RK3528 chipset box"),
    ("t982 box", "us", "T982 chipset box"),
    ("stbemu", "us", "STB Emu MAG clone"),
    ("mytvonline", "us", "MyTVOnline Formuler app"),
    ("libreelec box", "us", "LibreELEC firmware box"),
    ("emuelec box", "us", "EmuELEC firmware box"),
    ("plex iptv", "us", "Plex + IPTV playlist"),
    ("jellyfin iptv", "us", "Jellyfin + Live TV"),
    ("emby iptv", "us", "Emby Live TV"),
    ("avov box", "us", "Avov TVOnline box"),
    ("dreambox", "us", "DreamBox Enigma"),
    ("gigablue box", "us", "GigaBlue Enigma box"),
    ("octagon box", "us", "Octagon Enigma box"),
    ("h728 box", "us", "H728 chipset box"),
    ("rk3576 box", "us", "RK3576 chipset box"),
    ("t968 box", "us", "T968 chipset box"),
    ("rk3588s box", "us", "RK3588S chipset box"),
    ("s905m2 box", "us", "S905M2 chipset box"),
    ("h713 box", "us", "H713 chipset box"),
    ("rk3399 pro", "us", "RK3399 Pro chipset box"),
    ("minix box", "us", "MINIX Android box"),
    ("vu plus", "us", "VU+ Enigma box"),
    ("mutant box", "us", "Mutant Enigma box"),
    ("odroid box", "us", "ODROID media box"),
    ("khadas box", "us", "Khadas media box"),
    ("nexbox box", "us", "Nexbox Android box"),
    ("x96q box", "us", "X96Q Android box"),
    ("synology iptv", "us", "Synology Video Station"),
    ("channels dvr", "us", "Channels DVR Live TV"),
    ("x96 max", "us", "X96 Max Android box"),
    ("t950x box", "us", "T950X chipset box"),
    ("t972s box", "us", "T972S chipset box"),
    ("t968s box", "us", "T968S chipset box"),
    ("h313s box", "us", "H313S chipset box"),
    ("h618s box", "us", "H618S chipset box"),
    ("rk3566s box", "us", "RK3566S chipset box"),
    ("a95x box", "us", "A95X Android box"),
    ("tx3 box", "us", "Tanix TX3 box"),
    ("km2 box", "us", "Mecool KM2 box"),
    ("xteve", "us", "xTeVe IPTV proxy"),
    ("threadfin", "us", "Threadfin IPTV proxy"),
    ("kodi omega", "us", "Kodi Omega setup"),
    ("android tv", "us", "Android TV box setup"),
    ("h96 mini", "us", "H96 Mini Android box"),
    ("tx6 box", "us", "Tanix TX6 box"),
    ("t963x box", "us", "T963X chipset box"),
    ("t966s box", "us", "T966S chipset box"),
    ("km3 box", "us", "Mecool KM3 box"),
    ("km6 box", "us", "Mecool KM6 box"),
    ("km9 box", "us", "Mecool KM9 box"),
    ("tx9 box", "us", "TX9 Android box"),
    ("t95z box", "us", "T95Z Android box"),
    ("mx10 box", "us", "MX10 Android box"),
    ("ersatz tv", "us", "ErsatzTV playlist"),
    ("tunarr", "us", "Tunarr IPTV proxy"),
    ("kodi nexus", "us", "Kodi Nexus setup"),
    ("mag 322", "us", "MAG 322 box"),
    ("s905x5s box", "us", "S905X5S chipset box"),
    ("fire tv", "us", "Fire TV box setup"),
    ("km7 box", "us", "Mecool KM7 box"),
    ("mag 256", "us", "MAG 256 box"),
    ("mag 420", "us", "MAG 420 box"),
    ("dispatcharr", "us", "Dispatcharr IPTV proxy"),
    ("formuler z8", "us", "Formuler Z8 box"),
    ("formuler z10", "us", "Formuler Z10 box"),
    ("kodi matrix", "us", "Kodi Matrix setup"),
    ("google streamer", "us", "Google TV Streamer"),
    ("onn 4k", "us", "Onn 4K box"),
    ("m3u editor", "us", "M3U playlist editor"),
    ("rk3399s box", "us", "RK3399S chipset box"),
    ("t950e box", "us", "T950E chipset box"),
    ("formuler z11", "us", "Formuler Z11 box"),
    ("mag 324", "us", "MAG 324 box"),
    ("t95q box", "us", "T95Q Android box"),
    ("tx92 box", "us", "TX92 Android box"),
    ("a133s box", "us", "A133S chipset box"),
    ("kodi leia", "us", "Kodi Leia setup"),
    ("kodi krypton", "us", "Kodi Krypton setup"),
    ("superflix", "us", "SuperFlix app"),
    ("tivimate companion", "us", "TiviMate Companion app"),
    ("m3u4u", "us", "M3U4U playlist host"),
    ("iptv boss", "us", "IPTV Boss panel"),
    ("stremio", "us", "Stremio app"),
    ("infuse", "us", "Infuse player"),
    ("nplayer", "us", "nPlayer app"),
    ("cineplus", "us", "Cineplus app"),
    ("kodi addons", "us", "Kodi addons setup"),
    ("firestick 4k", "us", "Fire Stick 4K setup"),
    ("kodi jarvis", "us", "Kodi Jarvis setup"),
    ("kodi helix", "us", "Kodi Helix setup"),
    ("kodi isengard", "us", "Kodi Isengard setup"),
    ("kodi gotham", "us", "Kodi Gotham setup"),
    ("shield tv", "us", "Shield TV box"),
    ("smarttube", "us", "SmartTube YouTube client"),
    ("newpipe", "us", "NewPipe player"),
    ("libretube", "us", "LibreTube player"),
    ("grayjay", "us", "Grayjay player"),
    ("freetube", "us", "FreeTube player"),
    ("tvheadend", "us", "Tvheadend PVR"),
    ("nextpvr", "us", "NextPVR backend"),
    ("kodi pvr", "us", "Kodi PVR setup"),
    ("emby theater", "us", "Emby Theater app"),
    ("mx player", "us", "MX Player app"),
    ("nova player", "us", "Nova Player app"),
    ("iptvnator", "us", "IPTVnator playlist app"),
    ("hypnotix", "us", "Hypnotix IPTV app"),
    ("jellyfin theater", "us", "Jellyfin Theater app"),
    ("potplayer", "us", "PotPlayer app"),
    ("kmplayer", "us", "KMPlayer app"),
    ("mpv player", "us", "mpv player"),
    ("iina player", "us", "IINA player"),
    ("xbmc", "us", "XBMC media center"),
    ("osmc", "us", "OSMC media center"),
    ("spmc", "us", "SPMC Kodi fork"),
    ("synology video", "us", "Synology Video Station"),
    ("mythtv", "us", "MythTV PVR"),
    ("hdhomerun", "us", "HDHomeRun tuner"),
    ("tablo tv", "us", "Tablo TV tuner"),
    ("tautulli", "us", "Tautulli Plex stats"),
    ("overseerr", "us", "Overseerr requests"),
    ("jellyfin server", "us", "Jellyfin server setup"),
    ("emby server", "us", "Emby server setup"),
    ("plex server", "us", "Plex server setup"),
    ("kodi server", "us", "Kodi server setup"),
    ("silicondust", "us", "SiliconDust HDHomeRun"),
    ("minidlna", "us", "ReadyMedia MiniDLNA"),
    ("tizen tv", "us", "Samsung Tizen TV"),
    ("webos tv", "us", "LG webOS TV"),
    ("samsung tv", "us", "Samsung TV IPTV"),
    ("bravia tv", "us", "Sony Bravia TV"),
    ("hisense tv", "us", "Hisense VIDAA TV"),
    ("vizio tv", "us", "Vizio SmartCast TV"),
    ("vidaa tv", "us", "VIDAA smart TV"),
    ("roku tv", "us", "Roku TV setup"),
    ("jellyseerr", "us", "Jellyseerr requests"),
    ("plexamp", "us", "Plexamp app"),
    ("wetek box", "us", "WeTek Android box"),
    ("skyworth box", "us", "Skyworth Android box"),
    ("philips tv", "us", "Philips smart TV"),
    ("panasonic tv", "us", "Panasonic smart TV"),
    ("toshiba tv", "us", "Toshiba smart TV"),
    ("sharp tv", "us", "Sharp smart TV"),
    ("tcl tv", "us", "TCL Google TV"),
    ("realme tv", "us", "Realme smart TV"),
    ("oneplus tv", "us", "OnePlus TV"),
    ("xiaomi tv", "us", "Xiaomi smart TV"),
    ("sony tv", "us", "Sony smart TV"),
    ("xe player", "us", "XE Player app"),
    ("firestick lite", "us", "Fire Stick Lite"),
    ("firestick max", "us", "Fire Stick Max"),
    ("chromecast tv", "us", "Chromecast with Google TV"),
    ("nest hub", "us", "Google Nest Hub"),
    ("echo show", "us", "Amazon Echo Show"),
    ("playstation tv", "us", "PlayStation IPTV"),
    ("xbox tv", "us", "Xbox IPTV apps"),
    ("steam deck", "us", "Steam Deck media"),
    ("legion go", "us", "Legion Go handheld"),
    ("my iptv", "us", "MyIPTV player app"),
    ("mag player", "us", "MAG Player app"),
    ("epg guide", "us", "EPG guide setup"),
    ("smart stb", "us", "Smart STB MAG clone"),
    ("stalker portal", "us", "Stalker portal MAG"),
    ("ministra", "us", "Ministra middleware"),
    ("nebula player", "us", "Nebula IPTV player"),
    ("m3u playlist", "us", "M3U playlist setup"),
    ("xmltv guide", "us", "XMLTV EPG guide"),
    ("playlist editor", "us", "Playlist editor app"),
    ("mag portal", "us", "MAG portal setup"),
    ("dragon player", "us", "Dragon Player app"),
    ("t982s box", "us", "T982S chipset box"),
    ("tvip box", "us", "TVIP MAG box"),
    ("aurora player", "us", "Aurora IPTV player"),
    ("gplayer", "us", "GPlayer IPTV app"),
    ("xtream panel", "us", "Xtream Codes panel"),
    ("enigma2", "us", "Enigma2 image"),
    ("openatv", "us", "OpenATV Enigma image"),
    ("openpli", "us", "OpenPLi Enigma image"),
    ("rk3229s box", "us", "RK3229S chipset box"),
    ("bouquet editor", "us", "Enigma bouquet editor"),
    ("openvix", "us", "OpenViX Enigma image"),
    ("pureneos", "us", "PureNEXUS image"),
    ("egami", "us", "EGAMI Enigma image"),
    ("openelec", "us", "OpenELEC media center"),
    ("lakka", "us", "Lakka retro OS"),
    ("s905w2s box", "us", "S905W2S chipset box"),
    ("t968x box", "us", "T968X chipset box"),
    ("t950k box", "us", "T950K chipset box"),
    ("tivimate apk", "us", "TiviMate APK install"),
    ("rk3326s box", "us", "RK3326S chipset box"),
    ("h313 box", "us", "H313 chipset box"),
    ("a133 box", "us", "A133 chipset box"),
    ("openbh", "us", "OpenBH Enigma image"),
    ("opendroid", "us", "OpenDroid Enigma image"),
    ("opennfr", "us", "OpenNFR Enigma image"),
    ("teamblue", "us", "TeamBlue Enigma image"),
    ("openvision", "us", "OpenVision Enigma image"),
    ("kodi piers", "us", "Kodi Piers setup"),
    ("ott player", "us", "OTTPlayer app"),
    ("vti box", "us", "VTi Enigma image"),
    ("satdreamgr", "us", "SatDreamGr Enigma image"),
    ("sf8008", "us", "Octagon SF8008 box"),
    ("beelink gt1", "us", "Beelink GT1 box"),
    ("wetek play", "us", "WeTek Play box"),
    ("vu solo", "us", "VU+ Solo box"),
    ("rk3568s box", "us", "RK3568S chipset box"),
    ("t962s box", "us", "T962S chipset box"),
    ("t965s box", "us", "T965S chipset box"),
    ("h313e box", "us", "H313E chipset box"),
    ("openspa", "us", "OpenSPA Enigma image"),
    ("openhdf", "us", "OpenHDF Enigma image"),
    ("oscam", "us", "OSCam card client"),
    ("cccam", "us", "CCcam card client"),
    ("multics", "us", "Multics card client"),
    ("ncam", "us", "NCam card client"),
    ("torrentio", "us", "Torrentio Stremio addon"),
    ("stremio addon", "us", "Stremio addon setup"),
    ("tivimate beta", "us", "TiviMate beta app"),
    ("tivimate download", "us", "TiviMate download"),
    ("kodi seren", "us", "Kodi Seren addon"),
    ("kodi umbrella", "us", "Kodi Umbrella addon"),
    ("m3u8 player", "us", "M3U8 playlist player"),
    ("hls player", "us", "HLS stream player"),
    ("s905x4 box", "us", "S905X4 chipset box"),
    ("s905y4 box", "us", "S905Y4 chipset box"),
    ("t972e box", "us", "T972E chipset box"),
    ("a311ds box", "us", "A311DS chipset box"),
    ("real debrid", "us", "Real-Debrid Stremio"),
    ("alldebrid", "us", "AllDebrid Stremio"),
    ("premiumize", "us", "Premiumize Stremio"),
    ("mediafusion", "us", "MediaFusion addon"),
    ("kometa", "us", "Kometa Plex overlay"),
    ("xtream ui", "us", "Xtream UI panel"),
    ("xui one", "us", "XUI One panel"),
    ("sparkle apk", "us", "Sparkle TV APK"),
    ("smarters apk", "us", "Smarters Pro APK"),
    ("ibo apk", "us", "IBO Player APK"),
    ("kodi crew", "us", "Kodi Crew addon"),
    ("kodi exodus", "us", "Kodi Exodus addon"),
    ("kodi fen", "us", "Kodi Fen addon"),
    ("kodi gaia", "us", "Kodi Gaia addon"),
    ("kodi venom", "us", "Kodi Venom addon"),
    ("playlist manager", "us", "Playlist manager app"),
    ("sonarr", "us", "Sonarr PVR"),
    ("radarr", "us", "Radarr PVR"),
    ("lidarr", "us", "Lidarr PVR"),
    ("bazarr", "us", "Bazarr subtitles"),
    ("prowlarr", "us", "Prowlarr indexer"),
    ("tdarr", "us", "Tdarr transcode"),
    ("filelinked", "us", "FileLinked Fire Stick"),
    ("gse apk", "us", "GSE Smart IPTV APK"),
    ("xciptv apk", "us", "XCIPTV APK"),
    ("televizo apk", "us", "Televizo APK"),
    ("stremio apk", "us", "Stremio APK"),
    ("kodi apk", "us", "Kodi APK"),
    ("infuse apk", "us", "Infuse APK"),
    ("nplayer apk", "us", "nPlayer APK"),
    ("ss iptv apk", "us", "SS IPTV APK"),
    ("smart iptv apk", "us", "Smart IPTV APK"),
    ("downloader apk", "us", "Downloader APK"),
    ("kodi pov", "us", "Kodi POV addon"),
    ("kodi covenant", "us", "Kodi Covenant addon"),
    ("t963k box", "us", "T963K chipset box"),
    ("rk3399e box", "us", "RK3399E chipset box"),
    ("flix apk", "us", "Flix IPTV APK"),
    ("lazy apk", "us", "Lazy IPTV APK"),
    ("extreme apk", "us", "IPTV Extreme APK"),
    ("duplex apk", "us", "Duplex IPTV APK"),
    ("purple apk", "us", "Purple Player APK"),
    ("magis apk", "us", "Magis TV APK"),
    ("vlc apk", "us", "VLC APK"),
    ("mx apk", "us", "MX Player APK"),
    ("nova apk", "us", "Nova Player APK"),
    ("perfect apk", "us", "Perfect Player APK"),
    ("xe player apk", "us", "XE Player APK"),
    ("hypnotix apk", "us", "Hypnotix APK"),
    ("ibo pro apk", "us", "IBO Pro APK"),
    ("ott play apk", "us", "OTTplay APK"),
    ("readarr", "us", "Readarr PVR"),
    ("whisparr", "us", "Whisparr PVR"),
    ("t950m box", "us", "T950M chipset box"),
    ("s905x4s box", "us", "S905X4S chipset box"),
    ("jellyfin apk", "us", "Jellyfin APK"),
    ("plex apk", "us", "Plex APK"),
    ("emby apk", "us", "Emby APK"),
    ("smarttube apk", "us", "SmartTube APK"),
    ("newpipe apk", "us", "NewPipe APK"),
    ("tivimate pro", "us", "TiviMate Premium app"),
    ("smarters lite", "us", "Smarters Lite app"),
    ("ibo lite", "us", "IBO Lite app"),
    ("kodi placenta", "us", "Kodi Placenta addon"),
    ("kodi asgard", "us", "Kodi Asgard addon"),
    ("kodi shadow", "us", "Kodi Shadow addon"),
    ("autobrr", "us", "autobrr downloads"),
    ("recyclarr", "us", "Recyclarr sync"),
    ("notifiarr", "us", "Notifiarr alerts"),
    ("potplayer apk", "us", "PotPlayer APK"),
    ("t968k box", "us", "T968K chipset box"),
    ("rk3528s box", "us", "RK3528S chipset box"),
    ("grayjay apk", "us", "Grayjay APK"),
    ("freetube apk", "us", "FreeTube APK"),
    ("libretube apk", "us", "LibreTube APK"),
    ("firestick apk", "us", "Fire Stick APK"),
    ("kmplayer apk", "us", "KMPlayer APK"),
    ("mpv apk", "us", "mpv APK"),
    ("tautulli apk", "us", "Tautulli APK"),
    ("tvheadend apk", "us", "Tvheadend APK"),
    ("nextpvr apk", "us", "NextPVR APK"),
    ("kodi numbers", "us", "Kodi Numbers addon"),
    ("kodi dradis", "us", "Kodi Dradis addon"),
    ("chromecast apk", "us", "Chromecast APK"),
    ("t962k box", "us", "T962K chipset box"),
    ("h618e box", "us", "H618E chipset box"),
    ("osmc apk", "us", "OSMC APK"),
    ("spmc apk", "us", "SPMC APK"),
    ("xbmc apk", "us", "XBMC APK"),
    ("iina apk", "us", "IINA APK"),
    ("overseerr apk", "us", "Overseerr APK"),
    ("jellyseerr apk", "us", "Jellyseerr APK"),
    ("plexamp apk", "us", "Plexamp APK"),
    ("hdhomerun apk", "us", "HDHomeRun APK"),
    ("tablo apk", "us", "Tablo APK"),
    ("mythtv apk", "us", "MythTV APK"),
    ("synology apk", "us", "Synology APK"),
    ("sparkle lite", "us", "Sparkle Lite app"),
    ("t965e box", "us", "T965E chipset box"),
    ("rk3288s box", "us", "RK3288S chipset box"),
    ("xteve apk", "us", "xTeVe APK"),
    ("threadfin apk", "us", "Threadfin APK"),
    ("tunarr apk", "us", "Tunarr APK"),
    ("dispatcharr apk", "us", "Dispatcharr APK"),
    ("ersatz tv apk", "us", "ErsatzTV APK"),
    ("nebula apk", "us", "Nebula Player APK"),
    ("aurora apk", "us", "Aurora Player APK"),
    ("mag apk", "us", "MAG Player APK"),
    ("fire cube apk", "us", "Fire Cube APK"),
    ("roku apk", "us", "Roku APK"),
    ("apple tv apk", "us", "Apple TV APK"),
    ("onn apk", "us", "Onn box APK"),
    ("t972k box", "us", "T972K chipset box"),
    ("s905y4s box", "us", "S905Y4S chipset box"),
    ("google tv apk", "us", "Google TV APK"),
    ("android tv apk", "us", "Android TV APK"),
    ("tizen apk", "us", "Tizen APK"),
    ("webos apk", "us", "webOS APK"),
    ("bravia apk", "us", "Bravia APK"),
    ("hisense apk", "us", "Hisense APK"),
    ("vidaa apk", "us", "VIDAA APK"),
    ("shield apk", "us", "Shield TV APK"),
    ("gplayer apk", "us", "GPlayer APK"),
    ("dragon apk", "us", "Dragon Player APK"),
    ("xmltv apk", "us", "XMLTV APK"),
    ("t963m box", "us", "T963M chipset box"),
    ("vizio apk", "us", "Vizio APK"),
    ("tcl apk", "us", "TCL APK"),
    ("philips apk", "us", "Philips APK"),
    ("panasonic apk", "us", "Panasonic APK"),
    ("sony apk", "us", "Sony APK"),
    ("xiaomi apk", "us", "Xiaomi APK"),
    ("playstation apk", "us", "PlayStation APK"),
    ("xbox apk", "us", "Xbox APK"),
    ("steam deck apk", "us", "Steam Deck APK"),
    ("rk3328s box", "us", "RK3328S chipset box"),
    ("t950n box", "us", "T950N chipset box"),
    ("h313k box", "us", "H313K chipset box"),
    ("sharp apk", "us", "Sharp APK"),
    ("toshiba apk", "us", "Toshiba APK"),
    ("realme apk", "us", "Realme APK"),
    ("oneplus apk", "us", "OnePlus APK"),
    ("nest apk", "us", "Nest Hub APK"),
    ("echo show apk", "us", "Echo Show APK"),
    ("legion apk", "us", "Legion Go APK"),
    ("m3u apk", "us", "M3U player APK"),
    ("epg apk", "us", "EPG APK"),
    ("t968m box", "us", "T968M chipset box"),
    ("rk3562s box", "us", "RK3562S chipset box"),
    ("formuler apk", "us", "Formuler APK"),
    ("vontar apk", "us", "Vontar APK"),
    ("mecool apk", "us", "Mecool APK"),
    ("tanix apk", "us", "Tanix APK"),
    ("zidoo apk", "us", "Zidoo APK"),
    ("ugoos apk", "us", "Ugoos APK"),
    ("minix apk", "us", "MINIX APK"),
    ("wetek apk", "us", "WeTek APK"),
    ("beelink apk", "us", "Beelink APK"),
    ("t962m box", "us", "T962M chipset box"),
    ("s905x3s box", "us", "S905X3S chipset box"),
    ("nexbox apk", "us", "Nexbox APK"),
    ("odroid apk", "us", "ODROID APK"),
    ("khadas apk", "us", "Khadas APK"),
    ("mutant apk", "us", "Mutant APK"),
    ("vu plus apk", "us", "VU+ APK"),
    ("octagon apk", "us", "Octagon APK"),
    ("gigablue apk", "us", "GigaBlue APK"),
    ("dreambox apk", "us", "DreamBox APK"),
    ("avov apk", "us", "Avov APK"),
    ("zgemma apk", "us", "Zgemma APK"),
    ("t965k box", "us", "T965K chipset box"),
    ("rk3399k box", "us", "RK3399K chipset box"),
    ("dreamlink apk", "us", "Dreamlink APK"),
    ("buzz tv apk", "us", "BuzzTV APK"),
    ("infomir apk", "us", "Infomir APK"),
    ("uclan apk", "us", "UCLAN APK"),
    ("coreelec apk", "us", "CoreELEC APK"),
    ("libreelec apk", "us", "LibreELEC APK"),
    ("emuelec apk", "us", "EmuELEC APK"),
    ("openatv apk", "us", "OpenATV APK"),
    ("openpli apk", "us", "OpenPLi APK"),
    ("openvix apk", "us", "OpenViX APK"),
    ("t972m box", "us", "T972M chipset box"),
    ("h618k box", "us", "H618K chipset box"),
    ("openspa apk", "us", "OpenSPA APK"),
    ("openhdf apk", "us", "OpenHDF APK"),
    ("openbh apk", "us", "OpenBH APK"),
    ("opendroid apk", "us", "OpenDroid APK"),
    ("opennfr apk", "us", "OpenNFR APK"),
    ("teamblue apk", "us", "TeamBlue APK"),
    ("openvision apk", "us", "OpenVision APK"),
    ("egami apk", "us", "EGAMI APK"),
    ("openelec apk", "us", "OpenELEC APK"),
    ("lakka apk", "us", "Lakka APK"),
    ("t963n box", "us", "T963N chipset box"),
    ("rk3588k box", "us", "RK3588K chipset box"),
    ("mag 254 apk", "us", "MAG 254 APK"),
    ("stbemu apk", "us", "STB Emu APK"),
    ("mytvonline apk", "us", "MyTVOnline APK"),
    ("stalker apk", "us", "Stalker APK"),
    ("ministra apk", "us", "Ministra APK"),
    ("xtream apk", "us", "Xtream APK"),
    ("enigma2 apk", "us", "Enigma2 APK"),
    ("oscam apk", "us", "OSCam APK"),
    ("cccam apk", "us", "CCcam APK"),
    ("t972n box", "us", "T972N chipset box"),
    ("h618n box", "us", "H618N chipset box"),
    ("ncam apk", "us", "NCam APK"),
    ("multics apk", "us", "Multics APK"),
    ("torrentio apk", "us", "Torrentio APK"),
    ("pureneos apk", "us", "PureNEXUS APK"),
    ("satdreamgr apk", "us", "SatDreamGr APK"),
    ("vti apk", "us", "VTi APK"),
    ("bouquet apk", "us", "Bouquet editor APK"),
    ("t950p box", "us", "T950P chipset box"),
    ("s905x6s box", "us", "S905X6S chipset box"),
    ("dvbviewer apk", "us", "DVBViewer APK"),
    ("mediaportal apk", "us", "MediaPortal APK"),
    ("openwebif apk", "us", "OpenWebif APK"),
    ("t968p box", "us", "T968P chipset box"),
    ("h313p box", "us", "H313P chipset box"),
    ("syncler apk", "us", "Syncler APK"),
    ("iptvnator apk", "us", "IPTVnator APK"),
    ("cineplus apk", "us", "CinePlus APK"),
    ("m3u4u apk", "us", "M3U4U APK"),
    ("iptvboss apk", "us", "IPTV Boss APK"),
    ("superflix apk", "us", "Superflix APK"),
    ("seren apk", "us", "Seren Kodi addon APK"),
    ("umbrella apk", "us", "Umbrella Kodi addon APK"),
    ("covenant apk", "us", "Covenant Kodi addon APK"),
    ("exodus apk", "us", "Exodus Kodi addon APK"),
    ("venom apk", "us", "Venom Kodi addon APK"),
    ("wombat apk", "us", "Wombat Kodi addon APK"),
    ("minidlna apk", "us", "MiniDLNA APK"),
    ("companion apk", "us", "Kodi companion APK"),
    ("t962p box", "us", "T962P chipset box"),
    ("a133p box", "us", "A133P chipset box"),
    ("sonarr apk", "us", "Sonarr APK"),
    ("radarr apk", "us", "Radarr APK"),
    ("lidarr apk", "us", "Lidarr APK"),
    ("bazarr apk", "us", "Bazarr APK"),
    ("prowlarr apk", "us", "Prowlarr APK"),
    ("readarr apk", "us", "Readarr APK"),
    ("elementum apk", "us", "Elementum APK"),
    ("jackett apk", "us", "Jackett APK"),
    ("fenlight apk", "us", "Fen Light APK"),
    ("t965p box", "us", "T965P chipset box"),
    ("rk3562p box", "us", "RK3562P chipset box"),
    ("gaia apk", "us", "Gaia Kodi addon APK"),
    ("asgard apk", "us", "Asgard Kodi addon APK"),
    ("premiumize apk", "us", "Premiumize APK"),
    ("alldebrid apk", "us", "AllDebrid APK"),
    ("nzbhydra apk", "us", "NZBHydra APK"),
    ("sabnzbd apk", "us", "SABnzbd APK"),
    ("qbittorrent apk", "us", "qBittorrent APK"),
    ("t972p box", "us", "T972P chipset box"),
    ("h618p box", "us", "H618P chipset box"),
    ("mediafusion apk", "us", "MediaFusion APK"),
    ("whisparr apk", "us", "Whisparr APK"),
    ("comet apk", "us", "Comet Stremio addon APK"),
    ("nzbget apk", "us", "NZBGet APK"),
    ("deluge apk", "us", "Deluge APK"),
    ("transmission apk", "us", "Transmission APK"),
    ("t950r box", "us", "T950R chipset box"),
    ("s905w4s box", "us", "S905W4S chipset box"),
    ("trakt apk", "us", "Trakt APK"),
    ("simkl apk", "us", "SIMKL APK"),
    ("orion apk", "us", "Orion addon APK"),
    ("stremthru apk", "us", "StremThru APK"),
    ("jackettio apk", "us", "Jackettio APK"),
    ("aiostreams apk", "us", "AIOStreams APK"),
    ("t968r box", "us", "T968R chipset box"),
    ("h313r box", "us", "H313R chipset box"),
    ("mxplayer apk", "us", "MX Player APK"),
    ("justplayer apk", "us", "Just Player APK"),
    ("thecrew apk", "us", "The Crew addon APK"),
    ("nightwing apk", "us", "Nightwing addon APK"),
    ("annatar apk", "us", "Annatar Stremio APK"),
    ("knightcrawler apk", "us", "KnightCrawler APK"),
    ("t962r box", "us", "T962R chipset box"),
    ("rk3326r box", "us", "RK3326R chipset box"),
    ("kitsu apk", "us", "Kitsu APK"),
    ("anilist apk", "us", "AniList APK"),
    ("letterboxd apk", "us", "Letterboxd APK"),
    ("wizarr apk", "us", "Wizarr APK"),
    ("homarr apk", "us", "Homarr APK"),
    ("kavita apk", "us", "Kavita APK"),
    ("audiobookshelf apk", "us", "Audiobookshelf APK"),
    ("t965r box", "us", "T965R chipset box"),
    ("h618r box", "us", "H618R chipset box"),
    ("navidrome apk", "us", "Navidrome APK"),
    ("funkwhale apk", "us", "Funkwhale APK"),
    ("ampache apk", "us", "Ampache APK"),
    ("subsonic apk", "us", "Subsonic APK"),
    ("airsonic apk", "us", "Airsonic APK"),
    ("gonic apk", "us", "Gonic APK"),
    ("t972r box", "us", "T972R chipset box"),
    ("s905x7s box", "us", "S905X7S chipset box"),
    ("volumio apk", "us", "Volumio APK"),
    ("moode apk", "us", "Moode APK"),
    ("squeezelite apk", "us", "Squeezelite APK"),
    ("picoreplayer apk", "us", "piCorePlayer APK"),
    ("roon apk", "us", "Roon APK"),
    ("audirvana apk", "us", "Audirvana APK"),
    ("t950t box", "us", "T950T chipset box"),
    ("rk3568r box", "us", "RK3568R chipset box"),
    ("snapcast apk", "us", "Snapcast APK"),
    ("shairport apk", "us", "Shairport APK"),
    ("beets apk", "us", "Beets APK"),
    ("musicbrainz apk", "us", "MusicBrainz APK"),
    ("camilladsp apk", "us", "CamillaDSP APK"),
    ("mopidy apk", "us", "Mopidy APK"),
    ("t968t box", "us", "T968T chipset box"),
    ("h313t box", "us", "H313T chipset box"),
    ("strawberry apk", "us", "Strawberry player APK"),
    ("clementine apk", "us", "Clementine player APK"),
    ("rhythmbox apk", "us", "Rhythmbox APK"),
    ("lollypop apk", "us", "Lollypop APK"),
    ("deadbeef apk", "us", "DeaDBeeF APK"),
    ("foobar apk", "us", "foobar2000 APK"),
    ("t962t box", "us", "T962T chipset box"),
    ("a133t box", "us", "A133T chipset box"),
    ("haruna apk", "us", "Haruna player APK"),
    ("celluloid apk", "us", "Celluloid player APK"),
    ("smplayer apk", "us", "SMPlayer APK"),
    ("mpchc apk", "us", "MPC-HC APK"),
    ("mpcbe apk", "us", "MPC-BE APK"),
    ("t965t box", "us", "T965T chipset box"),
    ("rk3328t box", "us", "RK3328T chipset box"),
    ("outplayer apk", "us", "OutPlayer APK"),
    ("vidhub apk", "us", "VidHub APK"),
    ("senplayer apk", "us", "SenPlayer APK"),
    ("moonlight apk", "us", "Moonlight APK"),
    ("sunshine apk", "us", "Sunshine APK"),
    ("t972t box", "us", "T972T chipset box"),
    ("h618t box", "us", "H618T chipset box"),
    ("steamlink apk", "us", "Steam Link APK"),
    ("parsec apk", "us", "Parsec APK"),
    ("rustdesk apk", "us", "RustDesk APK"),
    ("nomachine apk", "us", "NoMachine APK"),
    ("chiaki apk", "us", "Chiaki APK"),
    ("t950u box", "us", "T950U chipset box"),
    ("rk3562t box", "us", "RK3562T chipset box"),
    ("waydroid apk", "us", "Waydroid APK"),
    ("redroid apk", "us", "Redroid APK"),
    ("blissos apk", "us", "Bliss OS APK"),
    ("primeos apk", "us", "PrimeOS APK"),
    ("phoenixos apk", "us", "Phoenix OS APK"),
    ("scrcpy apk", "us", "scrcpy APK"),
    ("t968u box", "us", "T968U chipset box"),
    ("h313u box", "us", "H313U chipset box"),
    ("lineageos apk", "us", "LineageOS APK"),
    ("grapheneos apk", "us", "GrapheneOS APK"),
    ("calyxos apk", "us", "CalyxOS APK"),
    ("microg apk", "us", "microG APK"),
    ("magisk apk", "us", "Magisk APK"),
    ("t962u box", "us", "T962U chipset box"),
    ("a133u box", "us", "A133U chipset box"),
    ("kernelsu apk", "us", "KernelSU APK"),
    ("lsposed apk", "us", "LSPosed APK"),
    ("zygisk apk", "us", "Zygisk APK"),
    ("shamiko apk", "us", "Shamiko APK"),
    ("t965u box", "us", "T965U chipset box"),
    ("rk3328u box", "us", "RK3328U chipset box"),
    ("fdroid apk", "us", "F-Droid APK"),
    ("obtainium apk", "us", "Obtainium APK"),
    ("neostore apk", "us", "Neo Store APK"),
    ("termux apk", "us", "Termux APK"),
    ("t972u box", "us", "T972U chipset box"),
    ("h618u box", "us", "H618U chipset box"),
    ("droidify apk", "us", "Droid-ify APK"),
    ("foxydroid apk", "us", "Foxy Droid APK"),
    ("shizuku apk", "us", "Shizuku APK"),
    ("apatch apk", "us", "APatch APK"),
    ("revanced apk", "us", "ReVanced APK"),
    ("pipepipe apk", "us", "PipePipe APK"),
    ("rk3568u box", "us", "RK3568U chipset box"),
    ("t968v box", "us", "T968V chipset box"),
    ("bromite apk", "us", "Bromite APK"),
    ("mull apk", "us", "Mull browser APK"),
    ("iceraven apk", "us", "Iceraven APK"),
    ("shelter apk", "us", "Shelter APK"),
    ("lawnchair apk", "us", "Lawnchair APK"),
    ("h313v box", "us", "H313V chipset box"),
    ("t972v box", "us", "T972V chipset box"),
    ("adaway apk", "us", "AdAway APK"),
    ("netguard apk", "us", "NetGuard APK"),
    ("swiftbackup apk", "us", "Swift Backup APK"),
    ("lspatch apk", "us", "LSPatch APK"),
    ("niagara apk", "us", "Niagara Launcher APK"),
    ("a133v box", "us", "A133V chipset box"),
    ("t965v box", "us", "T965V chipset box"),
    ("mixplorer apk", "us", "MiXplorer APK"),
    ("fossify apk", "us", "Fossify APK"),
    ("kvaesitso apk", "us", "Kvaesitso APK"),
    ("pixelxpert apk", "us", "PixelXpert APK"),
    ("smartlauncher apk", "us", "Smart Launcher APK"),
    ("rk3328v box", "us", "RK3328V chipset box"),
    ("fennec apk", "us", "Fennec APK"),
    ("organicmaps apk", "us", "Organic Maps APK"),
    ("beforelauncher apk", "us", "Before Launcher APK"),
    ("actionlauncher apk", "us", "Action Launcher APK"),
    ("simplegallery apk", "us", "Simple Gallery APK"),
    ("h618v box", "us", "H618V chipset box"),
    ("rk3562v box", "us", "RK3562V chipset box"),
    ("antennapod apk", "us", "AntennaPod APK"),
    ("fairmail apk", "us", "FairEmail APK"),
    ("k9mail apk", "us", "K-9 Mail APK"),
    ("osmand apk", "us", "OsmAnd APK"),
    ("fossifygallery apk", "us", "Fossify Gallery APK"),
    ("h313w box", "us", "H313W chipset box"),
    ("t950w box", "us", "T950W chipset box"),
    ("thunderbird apk", "us", "Thunderbird APK"),
    ("tusky apk", "us", "Tusky APK"),
    ("fedilab apk", "us", "Fedilab APK"),
    ("element apk", "us", "Element APK"),
    ("molly apk", "us", "Molly APK"),
    ("t962w box", "us", "T962W chipset box"),
    ("t968w box", "us", "T968W chipset box"),
    ("schildi apk", "us", "SchildiChat APK"),
    ("fluffychat apk", "us", "FluffyChat APK"),
    ("nheko apk", "us", "Nheko APK"),
    ("cinny apk", "us", "Cinny APK"),
    ("syphon apk", "us", "Syphon APK"),
    ("a133w box", "us", "A133W chipset box"),
    ("t965w box", "us", "T965W chipset box"),
    ("session apk", "us", "Session APK"),
    ("briar apk", "us", "Briar APK"),
    ("cwtch apk", "us", "Cwtch APK"),
    ("jami apk", "us", "Jami APK"),
    ("linphone apk", "us", "Linphone APK"),
    ("rk3328w box", "us", "RK3328W chipset box"),
    ("t972w box", "us", "T972W chipset box"),
    ("simplex apk", "us", "SimpleX APK"),
    ("threema apk", "us", "Threema APK"),
    ("wire app", "us", "Wire app APK"),
    ("delta chat", "us", "Delta Chat APK"),
    ("conversations apk", "us", "Conversations APK"),
    ("h618w box", "us", "H618W chipset box"),
    ("rk3568w box", "us", "RK3568W chipset box"),
    ("quassel apk", "us", "Quassel APK"),
    ("weechat apk", "us", "WeeChat APK"),
    ("hexchat apk", "us", "HexChat APK"),
    ("pidgin apk", "us", "Pidgin APK"),
    ("irssi apk", "us", "Irssi APK"),
    ("t950y box", "us", "T950Y chipset box"),
    ("h313y box", "us", "H313Y chipset box"),
    ("mattermost apk", "us", "Mattermost APK"),
    ("zulip apk", "us", "Zulip APK"),
    ("revolt apk", "us", "Revolt APK"),
    ("rocketchat apk", "us", "Rocket.Chat APK"),
    ("pumble apk", "us", "Pumble APK"),
    ("t968y box", "us", "T968Y chipset box"),
    ("t962y box", "us", "T962Y chipset box"),
    ("jitsi apk", "us", "Jitsi APK"),
    ("nextcloud apk", "us", "Nextcloud APK"),
    ("collabora apk", "us", "Collabora APK"),
    ("onlyoffice apk", "us", "ONLYOFFICE APK"),
    ("cryptpad apk", "us", "CryptPad APK"),
    ("t965y box", "us", "T965Y chipset box"),
    ("rk3328y box", "us", "RK3328Y chipset box"),
    ("seafile apk", "us", "Seafile APK"),
    ("syncthing apk", "us", "Syncthing APK"),
    ("photoprism apk", "us", "PhotoPrism APK"),
    ("filebrowser apk", "us", "File Browser APK"),
    ("duplicati apk", "us", "Duplicati APK"),
    ("a133y box", "us", "A133Y chipset box"),
    ("t972y box", "us", "T972Y chipset box"),
    ("restic apk", "us", "Restic APK"),
    ("borgbackup apk", "us", "BorgBackup APK"),
    ("kopia apk", "us", "Kopia APK"),
    ("rclone apk", "us", "Rclone APK"),
    ("duplicacy apk", "us", "Duplicacy APK"),
    ("h618y box", "us", "H618Y chipset box"),
    ("owncloud apk", "us", "ownCloud APK"),
    ("pcloud apk", "us", "pCloud APK"),
    ("internxt apk", "us", "Internxt APK"),
    ("protondrive apk", "us", "Proton Drive APK"),
    ("mega apk", "us", "MEGA APK"),
    ("t950z box", "us", "T950Z chipset box"),
    ("rk3562y box", "us", "RK3562Y chipset box"),
    ("filen apk", "us", "Filen APK"),
    ("tresorit apk", "us", "Tresorit APK"),
    ("icedrive apk", "us", "Icedrive APK"),
    ("koofr apk", "us", "Koofr APK"),
    ("synccom apk", "us", "Sync.com APK"),
    ("t968z box", "us", "T968Z chipset box"),
    ("h313z box", "us", "H313Z chipset box"),
    ("bitwarden apk", "us", "Bitwarden APK"),
    ("keepass apk", "us", "KeePass APK"),
    ("protonpass apk", "us", "Proton Pass APK"),
    ("1password apk", "us", "1Password APK"),
    ("dashlane apk", "us", "Dashlane APK"),
    ("t962z box", "us", "T962Z chipset box"),
    ("lastpass apk", "us", "LastPass APK"),
    ("nordpass apk", "us", "NordPass APK"),
    ("keepassxc apk", "us", "KeePassXC APK"),
    ("enpass apk", "us", "Enpass APK"),
    ("keeper apk", "us", "Keeper APK"),
    ("t965z box", "us", "T965Z chipset box"),
    ("aegis apk", "us", "Aegis APK"),
    ("2fas apk", "us", "2FAS APK"),
    ("authy apk", "us", "Authy APK"),
    ("andotp apk", "us", "andOTP APK"),
    ("raivo apk", "us", "Raivo APK"),
    ("a133z box", "us", "A133Z chipset box"),
)

# Map queued keyword -> domain needles (two-word focus TLDs).
NEEDLES = {
    "tivimate playlist": ("tivimate-playlist", "playlist-tivimate"),
    "tivimate setup": ("tivimate-setup",),
    "smarters pro": ("smarters-pro", "smarters-box", "smarters-player", "smarters-guide", "smarters-tv"),
    "ibo player": ("ibo-player", "ibo-box"),
    "ibo pro": ("ibo-pro", "ibopro-player", "ibo-smart"),
    "ott navigator": ("ott-navigator", "navigator-box"),
    "ott play": ("ott-play", "ottplay-box"),
    "gse smart iptv": ("gse-smart", "gse-player", "gse-box", "gse-guide"),
    "xtream codes": ("xtream-guide", "xtream-tivimate", "tivimate-xtream"),
    "xciptv": ("xciptv-box", "xciptv-player", "xciptv-guide"),
    "televizo": ("televizo-box", "televizo-player", "televizo-guide"),
    "ss iptv": ("ssiptv-box", "ssiptv-player"),
    "smart iptv": ("smartiptv-box",),
    "kodi iptv": ("kodi-guide", "kodi-player", "kodi-box", "tivimate-kodi"),
    "perfect player": ("perfect-player",),
    "lazy iptv": ("lazy-player", "lazyiptv-box"),
    "iptv extreme": ("extreme-player",),
    "duplex iptv": ("duplex-player", "duplex-box"),
    "purple player": ("purple-player", "purple-tv"),
    "flix iptv": ("flix-player", "flixiptv-box"),
    "magis tv": ("magis-tv", "magis-box"),
    "google tv iptv": ("googletv-box", "googletv-tivimate"),
    "onn box": ("onn-box", "onn-player"),
    "xiaomi iptv": ("xiaomi-box", "xiaomi-iptv"),
    "roku iptv": ("roku-guide",),
    "vlc iptv": ("vlc-player",),
    "apple tv iptv": ("appletv-box", "appletv-tivimate"),
    "fire cube iptv": ("firecube-box",),
    "british iptv": ("british-box", "british-guide", "british-iptv"),
    "beste iptv": ("beste-tivimate", "beste-box"),
    "bedste iptv": ("bedste-tivimate", "bedste-box"),
    "basta iptv": ("basta-tivimate", "basta-box"),
    "paras iptv": ("paras-tivimate", "paras-box"),
    "tivimate canada": ("tivimate-canada", "canada-tivimate", "tivimate-box"),
    "tivimate firestick": ("tivimate-firestick", "firestick-guide"),
    "sparkle iptv": ("sparkle-player", "sparkle-box", "sparkle-tv", "sparkle-guide"),
    "formuler iptv": ("formuler-box", "formuler-guide", "formuler-player"),
    "set iptv": ("setiptv-box",),
    "net iptv": ("netiptv-box",),
    "enigma iptv": ("enigma-box",),
    "iptv downloader": ("downloader-box",),
    "mag 254": ("mag254-box",),
    "infomir": ("infomir-box", "infomir-player"),
    "star box": ("starbox-guide",),
    "uclan iptv": ("uclan-guide", "uclan-tivimate"),
    "vontar box": ("vontar-box",),
    "h96 max": ("h96max-box",),
    "transpeed box": ("transpeed-box",),
    "hk1 max": ("hk1max-box",),
    "x88 pro": ("x88pro-box",),
    "t95 max": ("t95max-box",),
    "mxq pro": ("mxqpro-box",),
    "t95 mini": ("t95mini-box",),
    "x99 max": ("x99max-box",),
    "allwinner box": ("allwinner-box",),
    "amlogic box": ("amlogic-box",),
    "rockchip box": ("rockchip-box",),
    "s905x3 box": ("s905x3-box",),
    "s905w2 box": ("s905w2-box",),
    "a311d box": ("a311d-box",),
    "s922x box": ("s922x-box",),
    "rk3399 box": ("rk3399-box",),
    "s905x2 box": ("s905x2-box",),
    "rk3229 box": ("rk3229-box",),
    "s905l3 box": ("s905l3-box",),
    "rk3288 box": ("rk3288-box",),
    "s905x5 box": ("s905x5-box",),
    "s905l2 box": ("s905l2-box",),
    "mecool box": ("mecool-box",),
    "beelink box": ("beelink-box",),
    "tanix box": ("tanix-box",),
    "zidoo box": ("zidoo-box",),
    "ugoos box": ("ugoos-box",),
    "buzz tv": ("buzztv-box",),
    "dreamlink box": ("dreamlink-box",),
    "zgemma box": ("zgemma-box",),
    "chromecast iptv": ("chromecast-box",),
    "nvidia shield": ("nvidia-shield", "shield-box"),
    "coreelec box": ("coreelec-box",),
    "rk3528 box": ("rk3528-box",),
    "t982 box": ("t982-box",),
    "stbemu": ("stbemu-box",),
    "mytvonline": ("mytvonline-box",),
    "libreelec box": ("libreelec-box",),
    "emuelec box": ("emuelec-box",),
    "plex iptv": ("plex-box",),
    "jellyfin iptv": ("jellyfin-box",),
    "emby iptv": ("emby-box",),
    "avov box": ("avov-box",),
    "dreambox": ("dreambox-box",),
    "gigablue box": ("gigablue-box",),
    "octagon box": ("octagon-box",),
    "h728 box": ("h728-box",),
    "rk3576 box": ("rk3576-box",),
    "t968 box": ("t968-box",),
    "rk3588s box": ("rk3588s-box",),
    "s905m2 box": ("s905m2-box",),
    "h713 box": ("h713-box",),
    "rk3399 pro": ("rk3399pro-box",),
    "minix box": ("minix-box",),
    "vu plus": ("vuplus-box",),
    "mutant box": ("mutant-box",),
    "odroid box": ("odroid-box",),
    "khadas box": ("khadas-box",),
    "nexbox box": ("nexbox-box",),
    "x96q box": ("x96q-box",),
    "synology iptv": ("synology-box",),
    "channels dvr": ("channels-dvr",),
    "x96 max": ("x96max-box",),
    "t950x box": ("t950x-box",),
    "t972s box": ("t972s-box",),
    "t968s box": ("t968s-box",),
    "h313s box": ("h313s-box",),
    "h618s box": ("h618s-box",),
    "rk3566s box": ("rk3566s-box",),
    "a95x box": ("a95x-box",),
    "tx3 box": ("tx3-box",),
    "km2 box": ("km2-box",),
    "xteve": ("xteve-box",),
    "threadfin": ("threadfin-box",),
    "kodi omega": ("kodi-omega",),
    "android tv": ("android-tv",),
    "h96 mini": ("h96mini-box",),
    "tx6 box": ("tx6-box",),
    "t963x box": ("t963x-box",),
    "t966s box": ("t966s-box",),
    "km3 box": ("km3-box",),
    "km6 box": ("km6-box",),
    "km9 box": ("km9-box",),
    "tx9 box": ("tx9-box",),
    "t95z box": ("t95z-box",),
    "mx10 box": ("mx10-box",),
    "ersatz tv": ("ersatztv-box",),
    "tunarr": ("tunarr-box",),
    "kodi nexus": ("kodi-nexus",),
    "mag 322": ("mag322-box",),
    "s905x5s box": ("s905x5s-box",),
    "fire tv": ("firetv-box",),
    "km7 box": ("km7-box",),
    "mag 256": ("mag256-box",),
    "mag 420": ("mag420-box",),
    "dispatcharr": ("dispatcharr-box",),
    "formuler z8": ("formuler-z8",),
    "formuler z10": ("formuler-z10",),
    "kodi matrix": ("kodi-matrix",),
    "google streamer": ("google-streamer",),
    "onn 4k": ("onn-4k",),
    "m3u editor": ("m3u-editor",),
    "rk3399s box": ("rk3399s-box",),
    "t950e box": ("t950e-box",),
    "formuler z11": ("formuler-z11",),
    "mag 324": ("mag324-box",),
    "t95q box": ("t95q-box",),
    "tx92 box": ("tx92-box",),
    "a133s box": ("a133s-box",),
    "kodi leia": ("kodi-leia",),
    "kodi krypton": ("kodi-krypton",),
    "superflix": ("superflix-box",),
    "tivimate companion": ("tivimate-companion",),
    "m3u4u": ("m3u4u-box",),
    "iptv boss": ("iptvboss-box",),
    "stremio": ("stremio-box",),
    "infuse": ("infuse-box",),
    "nplayer": ("nplayer-box",),
    "cineplus": ("cineplus-box",),
    "kodi addons": ("kodi-addons",),
    "firestick 4k": ("firestick-4k",),
    "kodi jarvis": ("kodi-jarvis",),
    "kodi helix": ("kodi-helix",),
    "kodi isengard": ("kodi-isengard",),
    "kodi gotham": ("kodi-gotham",),
    "shield tv": ("shield-tv",),
    "smarttube": ("smarttube-box",),
    "newpipe": ("newpipe-box",),
    "libretube": ("libretube-box",),
    "grayjay": ("grayjay-box",),
    "freetube": ("freetube-box",),
    "tvheadend": ("tvheadend-box",),
    "nextpvr": ("nextpvr-box",),
    "kodi pvr": ("kodi-pvr",),
    "emby theater": ("emby-theater",),
    "mx player": ("mx-player",),
    "nova player": ("nova-player",),
    "iptvnator": ("iptvnator-box",),
    "hypnotix": ("hypnotix-box",),
    "jellyfin theater": ("jellyfin-theater",),
    "potplayer": ("potplayer-box",),
    "kmplayer": ("kmplayer-box",),
    "mpv player": ("mpv-player",),
    "iina player": ("iina-player",),
    "xbmc": ("xbmc-box",),
    "osmc": ("osmc-box",),
    "spmc": ("spmc-box",),
    "synology video": ("synology-video",),
    "mythtv": ("mythtv-box",),
    "hdhomerun": ("hdhomerun-box",),
    "tablo tv": ("tablo-box",),
    "tautulli": ("tautulli-box",),
    "overseerr": ("overseerr-box",),
    "jellyfin server": ("jellyfin-server",),
    "emby server": ("emby-server",),
    "plex server": ("plex-server",),
    "kodi server": ("kodi-server",),
    "silicondust": ("silicondust-box",),
    "minidlna": ("minidlna-box",),
    "tizen tv": ("tizen-tv",),
    "webos tv": ("webos-tv",),
    "samsung tv": ("samsung-tv",),
    "bravia tv": ("bravia-tv",),
    "hisense tv": ("hisense-tv",),
    "vizio tv": ("vizio-tv",),
    "vidaa tv": ("vidaa-tv",),
    "roku tv": ("roku-tv",),
    "jellyseerr": ("jellyseerr-box",),
    "plexamp": ("plexamp-box",),
    "wetek box": ("wetek-box",),
    "skyworth box": ("skyworth-box",),
    "philips tv": ("philips-tv",),
    "panasonic tv": ("panasonic-tv",),
    "toshiba tv": ("toshiba-tv",),
    "sharp tv": ("sharp-tv",),
    "tcl tv": ("tcl-tv",),
    "realme tv": ("realme-tv",),
    "oneplus tv": ("oneplus-tv",),
    "xiaomi tv": ("xiaomi-tv",),
    "sony tv": ("sony-tv",),
    "xe player": ("xeplayer-box",),
    "firestick lite": ("firestick-lite",),
    "firestick max": ("firestick-max",),
    "chromecast tv": ("chromecast-tv",),
    "nest hub": ("nest-hub",),
    "echo show": ("echoshow-box",),
    "playstation tv": ("playstation-tv",),
    "xbox tv": ("xbox-tv",),
    "steam deck": ("steamdeck-box",),
    "legion go": ("legion-go",),
    "my iptv": ("myiptv-box",),
    "mag player": ("mag-player",),
    "epg guide": ("epg-guide",),
    "smart stb": ("smart-stb",),
    "stalker portal": ("stalker-portal",),
    "ministra": ("ministra-box",),
    "nebula player": ("nebula-player",),
    "m3u playlist": ("m3u-playlist",),
    "xmltv guide": ("xmltv-guide",),
    "playlist editor": ("playlist-editor",),
    "mag portal": ("mag-portal",),
    "dragon player": ("dragon-player",),
    "t982s box": ("t982s-box",),
    "tvip box": ("tvip-box",),
    "aurora player": ("aurora-player",),
    "gplayer": ("gplayer-box",),
    "xtream panel": ("xtream-panel",),
    "enigma2": ("enigma2-box",),
    "openatv": ("openatv-box",),
    "openpli": ("openpli-box",),
    "rk3229s box": ("rk3229s-box",),
    "bouquet editor": ("bouquet-editor",),
    "openvix": ("openvix-box",),
    "pureneos": ("pureneos-box",),
    "egami": ("egami-box",),
    "openelec": ("openelec-box",),
    "lakka": ("lakka-box",),
    "s905w2s box": ("s905w2s-box",),
    "t968x box": ("t968x-box",),
    "t950k box": ("t950k-box",),
    "tivimate apk": ("tivimate-apk",),
    "rk3326s box": ("rk3326s-box",),
    "h313 box": ("h313-box",),
    "a133 box": ("a133-box",),
    "openbh": ("openbh-box",),
    "opendroid": ("opendroid-box",),
    "opennfr": ("opennfr-box",),
    "teamblue": ("teamblue-box",),
    "openvision": ("openvision-box",),
    "kodi piers": ("kodi-piers",),
    "ott player": ("ottplayer-box",),
    "vti box": ("vti-box",),
    "satdreamgr": ("satdreamgr-box",),
    "sf8008": ("sf8008-box",),
    "beelink gt1": ("beelink-gt1",),
    "wetek play": ("wetek-play",),
    "vu solo": ("vu-solo",),
    "rk3568s box": ("rk3568s-box",),
    "t962s box": ("t962s-box",),
    "t965s box": ("t965s-box",),
    "h313e box": ("h313e-box",),
    "openspa": ("openspa-box",),
    "openhdf": ("openhdf-box",),
    "oscam": ("oscam-box",),
    "cccam": ("cccam-box",),
    "multics": ("multics-box",),
    "ncam": ("ncam-box",),
    "torrentio": ("torrentio-box",),
    "stremio addon": ("stremio-addon",),
    "tivimate beta": ("tivimate-beta",),
    "tivimate download": ("tivimate-download",),
    "kodi seren": ("kodi-seren",),
    "kodi umbrella": ("kodi-umbrella",),
    "m3u8 player": ("m3u8-player",),
    "hls player": ("hls-player",),
    "s905x4 box": ("s905x4-box",),
    "s905y4 box": ("s905y4-box",),
    "t972e box": ("t972e-box",),
    "a311ds box": ("a311ds-box",),
    "real debrid": ("realdebrid-box",),
    "alldebrid": ("alldebrid-box",),
    "premiumize": ("premiumize-box",),
    "mediafusion": ("mediafusion-box",),
    "kometa": ("kometa-box",),
    "xtream ui": ("xtream-ui",),
    "xui one": ("xui-one",),
    "sparkle apk": ("sparkle-apk",),
    "smarters apk": ("smarters-apk",),
    "ibo apk": ("ibo-apk",),
    "kodi crew": ("kodi-crew",),
    "kodi exodus": ("kodi-exodus",),
    "kodi fen": ("kodi-fen",),
    "kodi gaia": ("kodi-gaia",),
    "kodi venom": ("kodi-venom",),
    "playlist manager": ("playlist-manager",),
    "sonarr": ("sonarr-box",),
    "radarr": ("radarr-box",),
    "lidarr": ("lidarr-box",),
    "bazarr": ("bazarr-box",),
    "prowlarr": ("prowlarr-box",),
    "tdarr": ("tdarr-box",),
    "filelinked": ("filelinked-box",),
    "gse apk": ("gse-apk",),
    "xciptv apk": ("xciptv-apk",),
    "televizo apk": ("televizo-apk",),
    "stremio apk": ("stremio-apk",),
    "kodi apk": ("kodi-apk",),
    "infuse apk": ("infuse-apk",),
    "nplayer apk": ("nplayer-apk",),
    "ss iptv apk": ("ssiptv-apk",),
    "smart iptv apk": ("smartiptv-apk",),
    "downloader apk": ("downloader-apk",),
    "kodi pov": ("kodi-pov",),
    "kodi covenant": ("kodi-covenant",),
    "t963k box": ("t963k-box",),
    "rk3399e box": ("rk3399e-box",),
    "flix apk": ("flix-apk",),
    "lazy apk": ("lazy-apk",),
    "extreme apk": ("extreme-apk",),
    "duplex apk": ("duplex-apk",),
    "purple apk": ("purple-apk",),
    "magis apk": ("magis-apk",),
    "vlc apk": ("vlc-apk",),
    "mx apk": ("mx-apk",),
    "nova apk": ("nova-apk",),
    "perfect apk": ("perfect-apk",),
    "xe player apk": ("xeplayer-apk",),
    "hypnotix apk": ("hypnotix-apk",),
    "ibo pro apk": ("ibopro-apk",),
    "ott play apk": ("ottplay-apk",),
    "readarr": ("readarr-box",),
    "whisparr": ("whisparr-box",),
    "t950m box": ("t950m-box",),
    "s905x4s box": ("s905x4s-box",),
    "jellyfin apk": ("jellyfin-apk",),
    "plex apk": ("plex-apk",),
    "emby apk": ("emby-apk",),
    "smarttube apk": ("smarttube-apk",),
    "newpipe apk": ("newpipe-apk",),
    "tivimate pro": ("tivimate-pro",),
    "smarters lite": ("smarters-lite",),
    "ibo lite": ("ibo-lite",),
    "kodi placenta": ("kodi-placenta",),
    "kodi asgard": ("kodi-asgard",),
    "kodi shadow": ("kodi-shadow",),
    "autobrr": ("autobrr-box",),
    "recyclarr": ("recyclarr-box",),
    "notifiarr": ("notifiarr-box",),
    "potplayer apk": ("potplayer-apk",),
    "t968k box": ("t968k-box",),
    "rk3528s box": ("rk3528s-box",),
    "grayjay apk": ("grayjay-apk",),
    "freetube apk": ("freetube-apk",),
    "libretube apk": ("libretube-apk",),
    "firestick apk": ("firestick-apk",),
    "kmplayer apk": ("kmplayer-apk",),
    "mpv apk": ("mpv-apk",),
    "tautulli apk": ("tautulli-apk",),
    "tvheadend apk": ("tvheadend-apk",),
    "nextpvr apk": ("nextpvr-apk",),
    "kodi numbers": ("kodi-numbers",),
    "kodi dradis": ("kodi-dradis",),
    "chromecast apk": ("chromecast-apk",),
    "t962k box": ("t962k-box",),
    "h618e box": ("h618e-box",),
    "osmc apk": ("osmc-apk",),
    "spmc apk": ("spmc-apk",),
    "xbmc apk": ("xbmc-apk",),
    "iina apk": ("iina-apk",),
    "overseerr apk": ("overseerr-apk",),
    "jellyseerr apk": ("jellyseerr-apk",),
    "plexamp apk": ("plexamp-apk",),
    "hdhomerun apk": ("hdhomerun-apk",),
    "tablo apk": ("tablo-apk",),
    "mythtv apk": ("mythtv-apk",),
    "synology apk": ("synology-apk",),
    "sparkle lite": ("sparkle-lite",),
    "t965e box": ("t965e-box",),
    "rk3288s box": ("rk3288s-box",),
    "xteve apk": ("xteve-apk",),
    "threadfin apk": ("threadfin-apk",),
    "tunarr apk": ("tunarr-apk",),
    "dispatcharr apk": ("dispatcharr-apk",),
    "ersatz tv apk": ("ersatztv-apk",),
    "nebula apk": ("nebula-apk",),
    "aurora apk": ("aurora-apk",),
    "mag apk": ("mag-apk",),
    "fire cube apk": ("firecube-apk",),
    "roku apk": ("roku-apk",),
    "apple tv apk": ("appletv-apk",),
    "onn apk": ("onn-apk",),
    "t972k box": ("t972k-box",),
    "s905y4s box": ("s905y4s-box",),
    "google tv apk": ("googletv-apk",),
    "android tv apk": ("androidtv-apk",),
    "tizen apk": ("tizen-apk",),
    "webos apk": ("webos-apk",),
    "bravia apk": ("bravia-apk",),
    "hisense apk": ("hisense-apk",),
    "vidaa apk": ("vidaa-apk",),
    "shield apk": ("shield-apk",),
    "gplayer apk": ("gplayer-apk",),
    "dragon apk": ("dragon-apk",),
    "xmltv apk": ("xmltv-apk",),
    "t963m box": ("t963m-box",),
    "vizio apk": ("vizio-apk",),
    "tcl apk": ("tcl-apk",),
    "philips apk": ("philips-apk",),
    "panasonic apk": ("panasonic-apk",),
    "sony apk": ("sony-apk",),
    "xiaomi apk": ("xiaomi-apk",),
    "playstation apk": ("playstation-apk",),
    "xbox apk": ("xbox-apk",),
    "steam deck apk": ("steamdeck-apk",),
    "rk3328s box": ("rk3328s-box",),
    "t950n box": ("t950n-box",),
    "h313k box": ("h313k-box",),
    "sharp apk": ("sharp-apk",),
    "toshiba apk": ("toshiba-apk",),
    "realme apk": ("realme-apk",),
    "oneplus apk": ("oneplus-apk",),
    "nest apk": ("nest-apk",),
    "echo show apk": ("echoshow-apk",),
    "legion apk": ("legion-apk",),
    "m3u apk": ("m3u-apk",),
    "epg apk": ("epg-apk",),
    "t968m box": ("t968m-box",),
    "rk3562s box": ("rk3562s-box",),
    "formuler apk": ("formuler-apk",),
    "vontar apk": ("vontar-apk",),
    "mecool apk": ("mecool-apk",),
    "tanix apk": ("tanix-apk",),
    "zidoo apk": ("zidoo-apk",),
    "ugoos apk": ("ugoos-apk",),
    "minix apk": ("minix-apk",),
    "wetek apk": ("wetek-apk",),
    "beelink apk": ("beelink-apk",),
    "t962m box": ("t962m-box",),
    "s905x3s box": ("s905x3s-box",),
    "nexbox apk": ("nexbox-apk",),
    "odroid apk": ("odroid-apk",),
    "khadas apk": ("khadas-apk",),
    "mutant apk": ("mutant-apk",),
    "vu plus apk": ("vuplus-apk",),
    "octagon apk": ("octagon-apk",),
    "gigablue apk": ("gigablue-apk",),
    "dreambox apk": ("dreambox-apk",),
    "avov apk": ("avov-apk",),
    "zgemma apk": ("zgemma-apk",),
    "t965k box": ("t965k-box",),
    "rk3399k box": ("rk3399k-box",),
    "dreamlink apk": ("dreamlink-apk",),
    "buzz tv apk": ("buzztv-apk",),
    "infomir apk": ("infomir-apk",),
    "uclan apk": ("uclan-apk",),
    "coreelec apk": ("coreelec-apk",),
    "libreelec apk": ("libreelec-apk",),
    "emuelec apk": ("emuelec-apk",),
    "openatv apk": ("openatv-apk",),
    "openpli apk": ("openpli-apk",),
    "openvix apk": ("openvix-apk",),
    "t972m box": ("t972m-box",),
    "h618k box": ("h618k-box",),
    "openspa apk": ("openspa-apk",),
    "openhdf apk": ("openhdf-apk",),
    "openbh apk": ("openbh-apk",),
    "opendroid apk": ("opendroid-apk",),
    "opennfr apk": ("opennfr-apk",),
    "teamblue apk": ("teamblue-apk",),
    "openvision apk": ("openvision-apk",),
    "egami apk": ("egami-apk",),
    "openelec apk": ("openelec-apk",),
    "lakka apk": ("lakka-apk",),
    "t963n box": ("t963n-box",),
    "rk3588k box": ("rk3588k-box",),
    "mag 254 apk": ("mag254-apk",),
    "stbemu apk": ("stbemu-apk",),
    "mytvonline apk": ("mytvonline-apk",),
    "stalker apk": ("stalker-apk",),
    "ministra apk": ("ministra-apk",),
    "xtream apk": ("xtream-apk",),
    "enigma2 apk": ("enigma2-apk",),
    "oscam apk": ("oscam-apk",),
    "cccam apk": ("cccam-apk",),
    "t972n box": ("t972n-box",),
    "h618n box": ("h618n-box",),
    "ncam apk": ("ncam-apk",),
    "multics apk": ("multics-apk",),
    "torrentio apk": ("torrentio-apk",),
    "pureneos apk": ("pureneos-apk",),
    "satdreamgr apk": ("satdreamgr-apk",),
    "vti apk": ("vti-apk",),
    "bouquet apk": ("bouquet-apk",),
    "t950p box": ("t950p-box",),
    "s905x6s box": ("s905x6s-box",),
    "dvbviewer apk": ("dvbviewer-apk",),
    "mediaportal apk": ("mediaportal-apk",),
    "openwebif apk": ("openwebif-apk",),
    "t968p box": ("t968p-box",),
    "h313p box": ("h313p-box",),
    "syncler apk": ("syncler-apk",),
    "iptvnator apk": ("iptvnator-apk",),
    "cineplus apk": ("cineplus-apk",),
    "m3u4u apk": ("m3u4u-apk",),
    "iptvboss apk": ("iptvboss-apk",),
    "superflix apk": ("superflix-apk",),
    "seren apk": ("seren-apk",),
    "umbrella apk": ("umbrella-apk",),
    "covenant apk": ("covenant-apk",),
    "exodus apk": ("exodus-apk",),
    "venom apk": ("venom-apk",),
    "wombat apk": ("wombat-apk",),
    "minidlna apk": ("minidlna-apk",),
    "companion apk": ("companion-apk",),
    "t962p box": ("t962p-box",),
    "a133p box": ("a133p-box",),
    "sonarr apk": ("sonarr-apk",),
    "radarr apk": ("radarr-apk",),
    "lidarr apk": ("lidarr-apk",),
    "bazarr apk": ("bazarr-apk",),
    "prowlarr apk": ("prowlarr-apk",),
    "readarr apk": ("readarr-apk",),
    "elementum apk": ("elementum-apk",),
    "jackett apk": ("jackett-apk",),
    "fenlight apk": ("fenlight-apk",),
    "t965p box": ("t965p-box",),
    "rk3562p box": ("rk3562p-box",),
    "gaia apk": ("gaia-apk",),
    "asgard apk": ("asgard-apk",),
    "premiumize apk": ("premiumize-apk",),
    "alldebrid apk": ("alldebrid-apk",),
    "nzbhydra apk": ("nzbhydra-apk",),
    "sabnzbd apk": ("sabnzbd-apk",),
    "qbittorrent apk": ("qbittorrent-apk",),
    "t972p box": ("t972p-box",),
    "h618p box": ("h618p-box",),
    "mediafusion apk": ("mediafusion-apk",),
    "whisparr apk": ("whisparr-apk",),
    "comet apk": ("comet-apk",),
    "nzbget apk": ("nzbget-apk",),
    "deluge apk": ("deluge-apk",),
    "transmission apk": ("transmission-apk",),
    "t950r box": ("t950r-box",),
    "s905w4s box": ("s905w4s-box",),
    "trakt apk": ("trakt-apk",),
    "simkl apk": ("simkl-apk",),
    "orion apk": ("orion-apk",),
    "stremthru apk": ("stremthru-apk",),
    "jackettio apk": ("jackettio-apk",),
    "aiostreams apk": ("aiostreams-apk",),
    "t968r box": ("t968r-box",),
    "h313r box": ("h313r-box",),
    "mxplayer apk": ("mxplayer-apk",),
    "justplayer apk": ("justplayer-apk",),
    "thecrew apk": ("thecrew-apk",),
    "nightwing apk": ("nightwing-apk",),
    "annatar apk": ("annatar-apk",),
    "knightcrawler apk": ("knightcrawler-apk",),
    "t962r box": ("t962r-box",),
    "rk3326r box": ("rk3326r-box",),
    "kitsu apk": ("kitsu-apk",),
    "anilist apk": ("anilist-apk",),
    "letterboxd apk": ("letterboxd-apk",),
    "wizarr apk": ("wizarr-apk",),
    "homarr apk": ("homarr-apk",),
    "kavita apk": ("kavita-apk",),
    "audiobookshelf apk": ("audiobookshelf-apk",),
    "t965r box": ("t965r-box",),
    "h618r box": ("h618r-box",),
    "navidrome apk": ("navidrome-apk",),
    "funkwhale apk": ("funkwhale-apk",),
    "ampache apk": ("ampache-apk",),
    "subsonic apk": ("subsonic-apk",),
    "airsonic apk": ("airsonic-apk",),
    "gonic apk": ("gonic-apk",),
    "t972r box": ("t972r-box",),
    "s905x7s box": ("s905x7s-box",),
    "volumio apk": ("volumio-apk",),
    "moode apk": ("moode-apk",),
    "squeezelite apk": ("squeezelite-apk",),
    "picoreplayer apk": ("picoreplayer-apk",),
    "roon apk": ("roon-apk",),
    "audirvana apk": ("audirvana-apk",),
    "t950t box": ("t950t-box",),
    "rk3568r box": ("rk3568r-box",),
    "snapcast apk": ("snapcast-apk",),
    "shairport apk": ("shairport-apk",),
    "beets apk": ("beets-apk",),
    "musicbrainz apk": ("musicbrainz-apk",),
    "camilladsp apk": ("camilladsp-apk",),
    "mopidy apk": ("mopidy-apk",),
    "t968t box": ("t968t-box",),
    "h313t box": ("h313t-box",),
    "strawberry apk": ("strawberry-apk",),
    "clementine apk": ("clementine-apk",),
    "rhythmbox apk": ("rhythmbox-apk",),
    "lollypop apk": ("lollypop-apk",),
    "deadbeef apk": ("deadbeef-apk",),
    "foobar apk": ("foobar-apk",),
    "t962t box": ("t962t-box",),
    "a133t box": ("a133t-box",),
    "haruna apk": ("haruna-apk",),
    "celluloid apk": ("celluloid-apk",),
    "smplayer apk": ("smplayer-apk",),
    "mpchc apk": ("mpchc-apk",),
    "mpcbe apk": ("mpcbe-apk",),
    "t965t box": ("t965t-box",),
    "rk3328t box": ("rk3328t-box",),
    "outplayer apk": ("outplayer-apk",),
    "vidhub apk": ("vidhub-apk",),
    "senplayer apk": ("senplayer-apk",),
    "moonlight apk": ("moonlight-apk",),
    "sunshine apk": ("sunshine-apk",),
    "t972t box": ("t972t-box",),
    "h618t box": ("h618t-box",),
    "steamlink apk": ("steamlink-apk",),
    "parsec apk": ("parsec-apk",),
    "rustdesk apk": ("rustdesk-apk",),
    "nomachine apk": ("nomachine-apk",),
    "chiaki apk": ("chiaki-apk",),
    "t950u box": ("t950u-box",),
    "rk3562t box": ("rk3562t-box",),
    "waydroid apk": ("waydroid-apk",),
    "redroid apk": ("redroid-apk",),
    "blissos apk": ("blissos-apk",),
    "primeos apk": ("primeos-apk",),
    "phoenixos apk": ("phoenixos-apk",),
    "scrcpy apk": ("scrcpy-apk",),
    "t968u box": ("t968u-box",),
    "h313u box": ("h313u-box",),
    "lineageos apk": ("lineageos-apk",),
    "grapheneos apk": ("grapheneos-apk",),
    "calyxos apk": ("calyxos-apk",),
    "microg apk": ("microg-apk",),
    "magisk apk": ("magisk-apk",),
    "t962u box": ("t962u-box",),
    "a133u box": ("a133u-box",),
    "kernelsu apk": ("kernelsu-apk",),
    "lsposed apk": ("lsposed-apk",),
    "zygisk apk": ("zygisk-apk",),
    "shamiko apk": ("shamiko-apk",),
    "t965u box": ("t965u-box",),
    "rk3328u box": ("rk3328u-box",),
    "fdroid apk": ("fdroid-apk",),
    "obtainium apk": ("obtainium-apk",),
    "neostore apk": ("neostore-apk",),
    "termux apk": ("termux-apk",),
    "t972u box": ("t972u-box",),
    "h618u box": ("h618u-box",),
    "droidify apk": ("droidify-apk",),
    "foxydroid apk": ("foxydroid-apk",),
    "shizuku apk": ("shizuku-apk",),
    "apatch apk": ("apatch-apk",),
    "revanced apk": ("revanced-apk",),
    "pipepipe apk": ("pipepipe-apk",),
    "rk3568u box": ("rk3568u-box",),
    "t968v box": ("t968v-box",),
    "bromite apk": ("bromite-apk",),
    "mull apk": ("mull-apk",),
    "iceraven apk": ("iceraven-apk",),
    "shelter apk": ("shelter-apk",),
    "lawnchair apk": ("lawnchair-apk",),
    "h313v box": ("h313v-box",),
    "t972v box": ("t972v-box",),
    "adaway apk": ("adaway-apk",),
    "netguard apk": ("netguard-apk",),
    "swiftbackup apk": ("swiftbackup-apk",),
    "lspatch apk": ("lspatch-apk",),
    "niagara apk": ("niagara-apk",),
    "a133v box": ("a133v-box",),
    "t965v box": ("t965v-box",),
    "mixplorer apk": ("mixplorer-apk",),
    "fossify apk": ("fossify-apk",),
    "kvaesitso apk": ("kvaesitso-apk",),
    "pixelxpert apk": ("pixelxpert-apk",),
    "smartlauncher apk": ("smartlauncher-apk",),
    "rk3328v box": ("rk3328v-box",),
    "fennec apk": ("fennec-apk",),
    "organicmaps apk": ("organicmaps-apk",),
    "beforelauncher apk": ("beforelauncher-apk",),
    "actionlauncher apk": ("actionlauncher-apk",),
    "simplegallery apk": ("simplegallery-apk",),
    "h618v box": ("h618v-box",),
    "rk3562v box": ("rk3562v-box",),
    "antennapod apk": ("antennapod-apk",),
    "fairmail apk": ("fairmail-apk",),
    "k9mail apk": ("k9mail-apk",),
    "osmand apk": ("osmand-apk",),
    "fossifygallery apk": ("fossifygallery-apk",),
    "h313w box": ("h313w-box",),
    "t950w box": ("t950w-box",),
    "thunderbird apk": ("thunderbird-apk",),
    "tusky apk": ("tusky-apk",),
    "fedilab apk": ("fedilab-apk",),
    "element apk": ("element-apk",),
    "molly apk": ("molly-apk",),
    "t962w box": ("t962w-box",),
    "t968w box": ("t968w-box",),
    "schildi apk": ("schildi-apk",),
    "fluffychat apk": ("fluffychat-apk",),
    "nheko apk": ("nheko-apk",),
    "cinny apk": ("cinny-apk",),
    "syphon apk": ("syphon-apk",),
    "a133w box": ("a133w-box",),
    "t965w box": ("t965w-box",),
    "session apk": ("session-apk",),
    "briar apk": ("briar-apk",),
    "cwtch apk": ("cwtch-apk",),
    "jami apk": ("jami-apk",),
    "linphone apk": ("linphone-apk",),
    "rk3328w box": ("rk3328w-box",),
    "t972w box": ("t972w-box",),
    "simplex apk": ("simplex-apk",),
    "threema apk": ("threema-apk",),
    "wire app": ("wireapp-apk",),
    "delta chat": ("deltachat-apk",),
    "conversations apk": ("conversations-apk",),
    "h618w box": ("h618w-box",),
    "rk3568w box": ("rk3568w-box",),
    "quassel apk": ("quassel-apk",),
    "weechat apk": ("weechat-apk",),
    "hexchat apk": ("hexchat-apk",),
    "pidgin apk": ("pidgin-apk",),
    "irssi apk": ("irssi-apk",),
    "t950y box": ("t950y-box",),
    "h313y box": ("h313y-box",),
    "mattermost apk": ("mattermost-apk",),
    "zulip apk": ("zulip-apk",),
    "revolt apk": ("revolt-apk",),
    "rocketchat apk": ("rocketchat-apk",),
    "pumble apk": ("pumble-apk",),
    "t968y box": ("t968y-box",),
    "t962y box": ("t962y-box",),
    "jitsi apk": ("jitsi-apk",),
    "nextcloud apk": ("nextcloud-apk",),
    "collabora apk": ("collabora-apk",),
    "onlyoffice apk": ("onlyoffice-apk",),
    "cryptpad apk": ("cryptpad-apk",),
    "t965y box": ("t965y-box",),
    "rk3328y box": ("rk3328y-box",),
    "seafile apk": ("seafile-apk",),
    "syncthing apk": ("syncthing-apk",),
    "photoprism apk": ("photoprism-apk",),
    "filebrowser apk": ("filebrowser-apk",),
    "duplicati apk": ("duplicati-apk",),
    "a133y box": ("a133y-box",),
    "t972y box": ("t972y-box",),
    "restic apk": ("restic-apk",),
    "borgbackup apk": ("borgbackup-apk",),
    "kopia apk": ("kopia-apk",),
    "rclone apk": ("rclone-apk",),
    "duplicacy apk": ("duplicacy-apk",),
    "h618y box": ("h618y-box",),
    "owncloud apk": ("owncloud-apk",),
    "pcloud apk": ("pcloud-apk",),
    "internxt apk": ("internxt-apk",),
    "protondrive apk": ("protondrive-apk",),
    "mega apk": ("mega-apk",),
    "t950z box": ("t950z-box",),
    "rk3562y box": ("rk3562y-box",),
    "filen apk": ("filen-apk",),
    "tresorit apk": ("tresorit-apk",),
    "icedrive apk": ("icedrive-apk",),
    "koofr apk": ("koofr-apk",),
    "synccom apk": ("synccom-apk",),
    "t968z box": ("t968z-box",),
    "h313z box": ("h313z-box",),
    "bitwarden apk": ("bitwarden-apk",),
    "keepass apk": ("keepass-apk",),
    "protonpass apk": ("protonpass-apk",),
    "1password apk": ("1password-apk",),
    "dashlane apk": ("dashlane-apk",),
    "t962z box": ("t962z-box",),
    "lastpass apk": ("lastpass-apk",),
    "nordpass apk": ("nordpass-apk",),
    "keepassxc apk": ("keepassxc-apk",),
    "enpass apk": ("enpass-apk",),
    "keeper apk": ("keeper-apk",),
    "t965z box": ("t965z-box",),
    "aegis apk": ("aegis-apk",),
    "2fas apk": ("2fas-apk",),
    "authy apk": ("authy-apk",),
    "andotp apk": ("andotp-apk",),
    "raivo apk": ("raivo-apk",),
    "a133z box": ("a133z-box",),
    "best iptv": ("compareiptv", "avis-iptv"),
    "iptv usa": ("usa-tivimate", "tivimate-usa"),
    "best iptv canada": ("compareiptv", "iptvguide"),
    "iptv uk": ("british-box", "british-guide"),
    "iptv firestick": ("firestick-guide", "tivimate-firestick"),
    "iptv subscription": ("tivimate-premium",),
}


def focus_tld(domain: str) -> bool:
    return any(domain.endswith(e) for e in FOCUS_ENDS)


MARKET_ENDS = {
    "ca": (".ca",),
    "us": (".us",),
    "uk": (".co.uk", ".uk"),
    "se": (".se",),
    "no": (".no",),
    "dk": (".dk",),
    "fi": (".fi",),
}


def available_focus(recheck: dict) -> list[str]:
    out = []
    for d, r in recheck.items():
        if r.get("verdict") != "AVAILABLE":
            continue
        if d.endswith(".se"):
            continue
        if skip_domain(d) or not focus_tld(d):
            continue
        out.append(d)
    return out


def needle_in_domain(domain: str, needle: str) -> bool:
    """Hyphen-bounded stem match so plex-box does not hit duplex-box."""
    n = (needle or "").lower().strip()
    if not n:
        return False
    label = domain_label(domain)
    return (
        label == n
        or label.startswith(n + "-")
        or label.endswith("-" + n)
        or f"-{n}-" in label
    )


def pick_leftover(needles: tuple[str, ...], pool: list[str], db: str = "") -> str:
    hits = []
    prefer = MARKET_ENDS.get(db, ())
    for d in pool:
        needle_i = next((i for i, n in enumerate(needles) if needle_in_domain(d, n)), None)
        if needle_i is None:
            continue
        pri = 0
        if prefer and d.endswith(prefer):
            pri = 10
        elif d.endswith(".ca"):
            pri = 3
        elif d.endswith(".us"):
            pri = 2
        elif d.endswith(".co.uk") or d.endswith(".uk"):
            pri = 2
        elif d.endswith((".dk", ".no", ".fi")):
            pri = 1
        hits.append((-pri, needle_i, d))
    hits.sort()
    if not hits:
        return "—"
    _pri, _needle_i, domain = hits[0]
    return domain


def score_row(k: dict) -> float:
    vol = int(k["volume"])
    kd = int(k.get("kd") or 0)
    return vol * (100 - kd) / 100.0


def main() -> None:
    traffic = json.loads(TRAFFIC.read_text(encoding="utf-8"))
    recheck = {}
    with RECHECK.open(encoding="utf-8") as f:
        for r in csv.DictReader(f):
            recheck[r["domain"]] = r

    pool = available_focus(recheck)

    verified = []
    for name, k in (traffic.get("keywords") or {}).items():
        if skip_keyword(name):
            continue
        if kd_is_excluded(k):
            continue
        try:
            vol = int(k["volume"])
        except (KeyError, TypeError, ValueError):
            continue
        if vol < MIN_VOLUME:
            continue
        db = (k.get("db") or "").lower()
        if db == "ie":
            continue
        if db not in FOCUS_DB and name not in {"iptv uk"}:
            continue
        leftover = pick_leftover(NEEDLES.get(name, (name.replace(" ", "-"),)), pool, db)
        verified.append(
            {
                "keyword": name,
                "market": FOCUS_LABEL.get(db, db),
                "vol": k.get("volume_display") or str(vol),
                "kd": f"{k.get('kd')} {k.get('kd_label') or ''}".strip(),
                "score": score_row(k),
                "why": k.get("intent") or "Commercial",
                "domain": leftover,
                "band": "verified",
            }
        )
    verified.sort(key=lambda r: -r["score"])

    queued = []
    seen = {r["keyword"] for r in verified}
    for name, db, why in QUEUED:
        if skip_keyword(name) or name in seen:
            continue
        leftover = pick_leftover(NEEDLES.get(name, (name.replace(" ", "-"),)), pool, db)
        seen.add(name)
        queued.append(
            {
                "keyword": name,
                "market": FOCUS_LABEL.get(db, db),
                "vol": "N/A",
                "kd": "N/A",
                "score": -1,
                "why": why,
                "domain": leftover,
                "band": "queued",
            }
        )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Ranked keywords (one table)",
        "",
        f"Updated {now}. **Only this file** is the keyword ranking. Real search queries (spaces). **No Semrush `keyword - keyword` pair rows.** No invented volumes. Difficult KD and volume < {MIN_VOLUME} are out. Focus leftovers: `.ca` `.us` `.co.uk`/`.uk` (no `iptv` in UK labels) `.dk` `.no` `.fi` — not `.fr`. `.se` UNKNOWN is not listed as a buy.",
        "",
        "| Rank | Keyword | Market | Vol / mo | KD | Score | Why it is strong | AVAILABLE leftover (focus TLD) |",
        "| ---: | --- | --- | ---: | --- | ---: | --- | --- |",
    ]
    rank = 1
    for r in verified:
        sc = f"{r['score']:.0f}"
        lines.append(
            f"| {rank} | `{r['keyword']}` | {r['market']} | {r['vol']} | {r['kd']} | {sc} | {r['why']} | `{r['domain']}` |"
        )
        rank += 1
    qn = 1
    for r in queued:
        lines.append(
            f"| Q{qn} | `{r['keyword']}` | {r['market']} | N/A | N/A | — | {r['why']} (Semrush pending) | `{r['domain']}` |"
        )
        qn += 1
    lines += [
        "",
        "Score = volume × (100 − KD) / 100 on verified rows only. Q-rows are participant app/platform queries with no Overview yet.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"WROTE {OUT} verified={len(verified)} queued={len(queued)}")


if __name__ == "__main__":
    main()
