#!/usr/bin/env python3
"""RDAP-check two-word app/box/server/subscription domains. No invented volumes."""

from __future__ import annotations

import csv
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from continue_research_batch import RDAP, has_dns, http_status, rdap_url, tld_of, verdict
from filters import is_two_word_domain, skip_domain

ROOT = Path(__file__).resolve().parent
RECHECK = ROOT / "availability_recheck.csv"

# Trusted country TLDs for this hunt. No .ie. No .uk names containing iptv.
TLDS = (".ca", ".us", ".fr", ".de", ".nl", ".ch", ".dk", ".no", ".se", ".fi")

# Generic two-word stems only. Brand app names stay SEO keywords, not EMDs.
STEMS = (
    "iptvbox",
    "iptv-box",
    "box-iptv",
    "iptvplayer",
    "iptv-player",
    "player-iptv",
    "iptvapp",
    "iptv-app",
    "app-iptv",
    "iptvserver",
    "iptv-server",
    "server-iptv",
    "iptvpanel",
    "iptv-panel",
    "panel-iptv",
    "iptvportal",
    "iptv-portal",
    "iptvreseller",
    "iptv-reseller",
    "reseller-iptv",
    "iptvplaylist",
    "iptv-playlist",
    "playlist-iptv",
    "iptvtrial",
    "iptv-trial",
    "trial-iptv",
    "iptvsetup",
    "iptv-setup",
    "setup-iptv",
    "iptvcodes",
    "iptv-codes",
    "xtream-iptv",
    "iptv-xtream",
    "m3u-iptv",
    "iptv-m3u",
    "mag-iptv",
    "iptv-mag",
    "magbox",
    "formuler-iptv",
    "formuler-box",
    "android-box",
    "android-iptv",
    "smart-box",
    "firestick-iptv",
    "firestick-box",
    "firetv-iptv",
    "roku-iptv",
    "appletv-iptv",
    "chromecast-iptv",
    "box-guide",
    "player-guide",
    "server-guide",
    "box-avis",
    "player-avis",
    "box-compare",
    "compare-box",
    "guide-box",
    "guide-player",
    "essai-box",
    "test-box",
    "vod-iptv",
    "iptv-vod",
    "premium-iptv",
    "iptv-premium",
    "stick-iptv",
    "iptv-stick",
    "shield-iptv",
    "nvidia-iptv",
    "iptv-abo",
    "abo-iptv",
    "live-iptv",
    "iptv-live",
    "stream-iptv",
    "iptv-stream",
    "watch-iptv",
    "iptv-watch",
    "legal-iptv",
    "iptv-legal",
    "cheap-iptv",
    "iptv-cheap",
    "deals-iptv",
    "iptv-deals",
    "plans-iptv",
    "iptv-plans",
    "review-iptv",
    "iptv-review",
    "ott-iptv",
    "iptv-ott",
    "4k-iptv",
    "iptv-4k",
    "cordcut-iptv",
    "paytv-iptv",
    "anbieter-iptv",
    "iptv-anbieter",
    "gids-iptv",
    "iptv-gids",
    "avis-box",
    "compare-player",
    "player-compare",
    "iptv-test",
    "test-iptv",
    "avis-iptv",
    "essai-iptv",
    "forfait-iptv",
    "meilleur-iptv",
    "comparer-iptv",
    "comparateur-iptv",
    "pascher-iptv",
    "abonnement-iptv",
    "vergleich-iptv",
    "beste-iptv",
    "kaufen-iptv",
    "guenstig-iptv",
    "vergelijk-iptv",
    "goedkope-iptv",
    "mejor-iptv",
    "barato-iptv",
    "prueba-iptv",
    "comparar-iptv",
    "guia-iptv",
    "migliore-iptv",
    "miglior-iptv",
    "prova-iptv",
    "guida-iptv",
    "confronta-iptv",
    "melhor-iptv",
    "basta-iptv",
    "jamfor-iptv",
    "bedste-iptv",
    "billig-iptv",
    "paras-iptv",
    "vertaa-iptv",
    "halpa-iptv",
    "sammenlign-iptv",
    "player-box",
    "server-box",
    "m3u-player",
    "xtream-player",
    "ott-player",
    "ott-box",
    "mag-player",
    "mag-server",
    "formuler-player",
    "roku-box",
    "roku-player",
    "shield-box",
    "firetv-box",
    "android-player",
    "smart-player",
    "vod-box",
    "vod-player",
    "live-box",
    "live-player",
    "stream-box",
    "stream-player",
    "watch-box",
    "watch-guide",
    "legal-guide",
    "review-box",
    "review-guide",
    "rating-box",
    "rating-iptv",
    "rank-iptv",
    "picks-iptv",
    "codes-player",
    "playlist-player",
    "panel-box",
    "portal-box",
    "trial-box",
    "setup-box",
    "setup-player",
    "abo-box",
    "box-abo",
    "forfait-box",
    "decoder-iptv",
    "iptv-decoder",
    "kodi-iptv",
    "vlc-iptv",
    "downloader-iptv",
    "enigma-iptv",
    "zgemma-iptv",
    "iptv-abonnement",
    "aanbieder-iptv",
    "iptv-aanbieder",
    "proberen-iptv",
    "abbonamento-iptv",
    "suscripcion-iptv",
    "legale-iptv",
    "iptv-legale",
    "iptv-norge",
    "iptv-danmark",
    "iptv-suomi",
    "iptv-sverige",
    "iptv-nederland",
    "iptv-deutschland",
    "iptv-suisse",
    "iptv-schweiz",
    "iptv-quebec",
    "quebec-iptv",
    "m3u-box",
    "xtream-box",
    "codes-box",
    "reseller-box",
    "reseller-panel",
    "panel-server",
    "server-panel",
    "vod-guide",
    "4k-box",
    "4k-player",
    "legal-box",
    "cheap-box",
    "cheap-player",
    "trial-player",
    "trial-app",
    "setup-app",
    "player-app",
    "app-player",
    "app-box",
    "box-app",
    "mag-box",
    "firetv-player",
    "chromecast-box",
    "chromecast-player",
    "appletv-box",
    "appletv-player",
    "shield-player",
    "nvidia-box",
    "nvidia-player",
    "epg-iptv",
    "iptv-epg",
    "epg-box",
    "catchup-iptv",
    "iptv-catchup",
    "replay-iptv",
    "iptv-replay",
    "sport-iptv",
    "iptv-sport",
    "sport-box",
    "film-iptv",
    "iptv-film",
    "film-box",
    "films-iptv",
    "chaines-iptv",
    "sender-iptv",
    "kanal-iptv",
    "stb-iptv",
    "iptv-stb",
    "vod-abo",
    "abo-vod",
    "live-guide",
    "live-epg",
    "sport-guide",
    "film-guide",
    "epg-guide",
    "replay-box",
    "catchup-box",
    "stb-box",
    "stb-player",
    "movie-iptv",
    "movie-box",
    "kids-iptv",
    "iptv-kids",
    "news-iptv",
    "iptv-news",
    "pvr-iptv",
    "iptv-pvr",
    "timeshift-iptv",
    "install-iptv",
    "iptv-install",
    "config-iptv",
    "iptv-config",
    "hdr-iptv",
    "hevc-iptv",
    "kids-box",
    "news-box",
    "pvr-box",
    "install-box",
    "install-player",
    "config-box",
    "hdr-box",
    "hevc-box",
)

# Local cities × iptv on the matching country TLD (still two words).
CITY_BY_TLD = {
    ".fr": (
        "paris",
        "lyon",
        "marseille",
        "toulouse",
        "lille",
        "nantes",
        "bordeaux",
        "nice",
        "reims",
        "dijon",
        "angers",
        "strasbourg",
        "rennes",
        "montpellier",
        "grenoble",
        "toulon",
        "lehavre",
        "clermont",
        "limoges",
        "amiens",
        "perpignan",
    ),
    ".ca": (
        "toronto",
        "montreal",
        "vancouver",
        "calgary",
        "ottawa",
        "edmonton",
        "winnipeg",
        "halifax",
        "hamilton",
        "brampton",
        "mississauga",
        "quebec",
        "ontario",
        "alberta",
        "kelowna",
        "windsor",
        "saskatoon",
        "regina",
        "victoria",
        "london",
        "gatineau",
        "laval",
    ),
    ".us": (
        "houston",
        "dallas",
        "miami",
        "atlanta",
        "seattle",
        "denver",
        "boston",
        "detroit",
        "austin",
        "nashville",
        "portland",
        "charlotte",
        "chicago",
        "phoenix",
        "philadelphia",
        "minneapolis",
        "tampa",
        "orlando",
        "cleveland",
        "columbus",
        "indianapolis",
        "baltimore",
        "sacramento",
        "raleigh",
        "saltlake",
    ),
    ".de": (
        "berlin",
        "hamburg",
        "muenchen",
        "frankfurt",
        "stuttgart",
        "koeln",
        "duesseldorf",
        "hannover",
        "leipzig",
        "dresden",
        "nurnberg",
        "bremen",
        "dortmund",
        "essen",
    ),
    ".nl": (
        "amsterdam",
        "rotterdam",
        "utrecht",
        "eindhoven",
        "denhaag",
        "groningen",
        "tilburg",
        "breda",
        "almere",
        "arnhem",
        "nijmegen",
    ),
    ".ch": (
        "zurich",
        "geneve",
        "lausanne",
        "bern",
        "basel",
        "lugano",
        "winterthur",
        "luzern",
        "stgallen",
    ),
    ".no": ("oslo", "bergen", "trondheim", "stavanger", "tromso"),
    ".dk": ("kobenhavn", "aarhus", "odense", "aalborg"),
    ".fi": ("helsinki", "tampere", "oulu", "turku", "jyvaskyla"),
    ".se": ("stockholm", "malmo", "goteborg", "uppsala", "orebro", "linkoping"),
}


def _push(domain: str, seen: set[str], out: list[str]) -> None:
    if domain in seen:
        return
    if skip_domain(domain) or not is_two_word_domain(domain):
        return
    seen.add(domain)
    out.append(domain)


def candidates() -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for stem in STEMS:
        for tld in TLDS:
            _push(f"{stem}{tld}", seen, out)
    for tld, cities in CITY_BY_TLD.items():
        for city in cities:
            _push(f"{city}-iptv{tld}", seen, out)
            _push(f"iptv-{city}{tld}", seen, out)
    return out


def main() -> None:
    existing: dict[str, dict] = {}
    if RECHECK.exists():
        with RECHECK.open(encoding="utf-8") as f:
            for r in csv.DictReader(f):
                existing[r["domain"]] = r

    todo = [d for d in candidates() if d not in existing]
    print(f"universe={len(candidates())} already={len(existing)} todo={len(todo)}")

    new_avail = []
    done = 0

    def check(domain: str) -> tuple[str, dict]:
        code, dns, v = verdict(domain)
        return domain, {
            "domain": domain,
            "rdap": "" if code is None else str(code),
            "dns": "yes" if dns else "no",
            "verdict": v,
        }

    with ThreadPoolExecutor(max_workers=8) as pool:
        futs = [pool.submit(check, d) for d in todo]
        for fut in as_completed(futs):
            domain, row = fut.result()
            existing[domain] = row
            done += 1
            if row["verdict"] == "AVAILABLE":
                new_avail.append(domain)
            print(f"{done:3}/{len(todo)} {domain:32} rdap={row['rdap']:4} dns={row['dns']:3} {row['verdict']}")

    with RECHECK.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["domain", "rdap", "dns", "verdict"])
        w.writeheader()
        for d in sorted(existing):
            w.writerow(existing[d])

    print("NEW_AVAILABLE", len(new_avail))
    for d in new_avail:
        print(" ", d)


if __name__ == "__main__":
    # Keep unused imports honest for static checkers.
    _ = (RDAP, has_dns, http_status, rdap_url, tld_of)
    main()
